; Auto-generated by copy-webview2-dll.mjs
; Installs WebView2Loader.dll alongside the EXE.
!macro NSIS_HOOK_POSTINSTALL
  File "/oname=$INSTDIR\WebView2Loader.dll" "D:\\lumiOS\\src-tauri\\target\\release\\WebView2Loader.dll"
!macroend
