export { queryMemories, queryMemoriesVector, backfillEmbeddings, addMemory, removeMemory, decayMemories, dynamicDecayMemories, computeMemoryValue, promoteMemories, formatMemoriesForContext, addReminder, getDueReminders, fireReminder, getUnconsolidatedEpisodic, markConsolidated, decayMemoryAssociations, initMemoryAssociations, getAssociatedMemories, borrowAgentMemories, autoMarkCrossAgentShare } from './store';
export type { Reminder } from './store';
export { extractMemories } from './extractor';
export type { ExtractedMemory, MemoryTier, MemoryPerspective } from './types';
export type { ExtractedReminder } from './extractor';
export { analyzeBehavioralPatterns, runBehavioralAnalysis } from './behavioral';
export type { BehavioralPattern } from './behavioral';
export { initMemorySync, registerUserSocket, unregisterUserSocket, broadcastMemoryChange, broadcastDeviceChange, broadcastPreferenceChange } from './sync';
export { buildNarrativeChain } from './narrative';
export type { NarrativeChainResult } from './narrative';
