// Polyfill WebSocket for Node.js (required by MCP SDK's WebSocket transport)
import { WebSocket } from 'ws';
globalThis.WebSocket = WebSocket as any;

import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { StdioClientTransport } from '@modelcontextprotocol/sdk/client/stdio.js';
import { StreamableHTTPClientTransport } from '@modelcontextprotocol/sdk/client/streamableHttp.js';
import { WebSocketClientTransport } from '@modelcontextprotocol/sdk/client/websocket.js';
import fs from 'fs';
import path from 'path';
import os from 'os';
import { exec } from 'child_process';

export interface MCPServerConfig {
  command?: string;
  args?: string[];
  env?: Record<string, string>;
  enabled: boolean;
  source?: 'local' | 'external';      // local = Lumi skill dir, external = third-party
  transport?: 'stdio' | 'http' | 'ws'; // stdio = local process, http = HTTP, ws = WebSocket
  url?: string;                         // URL for remote MCP server (http/ws transport)
  headers?: Record<string, string>;    // custom auth headers for remote connection
  autoGenerated?: boolean;             // true if Lumi generated this skill
  generatedFrom?: string;              // trace: conversation ID or workflow ID
  description?: string;                // human-readable description
  toolCount?: number;                  // cached tool count for UI
}

export interface MCPToolDef {
  serverName: string;
  name: string;
  description?: string;
  inputSchema: Record<string, any>;
}

export interface SkillPackage {
  name: string;          // directory name / skill id
  description: string;
  toolCount: number;
  autoGenerated: boolean;
  generatedFrom?: string;
  installedAt: string;
  source: 'local' | 'external';
}

interface ConnectedServer {
  client: Client;
  transport: StdioClientTransport | StreamableHTTPClientTransport | WebSocketClientTransport;
  config: MCPServerConfig;
}

const SKILLS_DIR = path.join(os.homedir(), 'lumi_skills');

interface CrashTracker {
  consecutiveCrashes: number;
  lastCrashTime: string;
  lastSuccessfulConnect: string;
  restartTimer: ReturnType<typeof setTimeout> | null;
}

class MCPClientManager {
  private servers: Map<string, ConnectedServer> = new Map();
  private configPath: string;
  private crashTrackers: Map<string, CrashTracker> = new Map();
  private closingSet: Set<string> = new Set();
  private onServerRecovered?: (name: string, tools: MCPToolDef[]) => void;
  private ioRef?: any;

  constructor(configPath?: string) {
    this.configPath = configPath || path.join(process.cwd(), 'server', 'mcp', 'config.json');
  }

  setSocketIO(io: any): void { this.ioRef = io; }
  setOnServerRecovered(cb: (name: string, tools: MCPToolDef[]) => void): void { this.onServerRecovered = cb; }

  getConfig(): Record<string, MCPServerConfig> {
    try {
      const raw = fs.readFileSync(this.configPath, 'utf-8');
      const parsed = JSON.parse(raw);
      return parsed.mcpServers || {};
    } catch {
      return {};
    }
  }

  saveConfig(servers: Record<string, MCPServerConfig>): void {
    const dir = path.dirname(this.configPath);
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
    fs.writeFileSync(this.configPath, JSON.stringify({ mcpServers: servers }, null, 2));
  }

  // ── Local skill directory management ──

  /** Ensure the skills directory exists */
  private ensureSkillsDir(): void {
    if (!fs.existsSync(SKILLS_DIR)) {
      fs.mkdirSync(SKILLS_DIR, { recursive: true });
    }
  }

  /** List all local skills in ~/lumi_skills/ */
  listLocalSkills(): SkillPackage[] {
    this.ensureSkillsDir();
    const skills: SkillPackage[] = [];
    const entries = fs.readdirSync(SKILLS_DIR, { withFileTypes: true });

    for (const entry of entries) {
      if (!entry.isDirectory()) continue;
      const skillDir = path.join(SKILLS_DIR, entry.name);
      const pkgPath = path.join(skillDir, 'package.json');
      const indexPath = path.join(skillDir, 'index.ts');

      if (!fs.existsSync(indexPath)) continue;

      let pkg: any = {};
      try { pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf-8')); } catch {}

      skills.push({
        name: entry.name,
        description: pkg.description || pkg.lumi?.description || entry.name,
        toolCount: pkg.lumi?.toolCount || 0,
        autoGenerated: pkg.lumi?.autoGenerated || false,
        generatedFrom: pkg.lumi?.generatedFrom,
        installedAt: pkg.lumi?.installedAt || '',
        source: 'local',
      });
    }
    return skills;
  }

  /** Install a skill from a source directory into ~/lumi_skills/ */
  installSkill(name: string, sourceDir: string): string {
    this.ensureSkillsDir();
    const destDir = path.join(SKILLS_DIR, name);

    if (fs.existsSync(destDir)) {
      throw new Error(`Skill "${name}" already exists. Uninstall it first.`);
    }

    this.copyDirSync(sourceDir, destDir);

    // Run npm install in the destination so deps are available at runtime
    this.installDepsInDir(destDir);

    // Write install metadata into package.json
    const pkgPath = path.join(destDir, 'package.json');
    let pkg: any = {};
    try { pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf-8')); } catch {}
    if (!pkg.lumi) pkg.lumi = {};
    pkg.lumi.installedAt = new Date().toISOString();
    pkg.lumi.autoGenerated = pkg.lumi.autoGenerated || false;
    fs.writeFileSync(pkgPath, JSON.stringify(pkg, null, 2));

    // Add to config.json
    this.registerLocalSkill(name, destDir, pkg);

    return destDir;
  }

  /** Uninstall a local skill */
  uninstallSkill(name: string): void {
    const skillDir = path.join(SKILLS_DIR, name);
    if (fs.existsSync(skillDir)) {
      fs.rmSync(skillDir, { recursive: true, force: true });
    }

    // Remove from config.json
    const config = this.getConfig();
    if (config[name]) {
      delete config[name];
      this.saveConfig(config);
    }
  }

  /** Register a skill directory as an MCP server entry in config.json */
  private registerLocalSkill(name: string, skillDir: string, pkg: any): void {
    const config = this.getConfig();
    const lumi = pkg.lumi || {};

    // Support external MCP packages with custom run commands
    if (lumi.runCommand) {
      config[name] = {
        command: lumi.runCommand,
        args: lumi.runArgs || [],
        env: lumi.requiresApiKey && lumi.apiKeyEnv
          ? { [lumi.apiKeyEnv]: `\${${lumi.apiKeyEnv}}` }
          : undefined,
        enabled: !lumi.requiresApiKey, // Disable by default if API key needed
        source: 'local',
        transport: 'stdio',
        autoGenerated: lumi.autoGenerated || false,
        generatedFrom: lumi.generatedFrom,
        description: pkg.description || lumi.description || name,
        toolCount: lumi.toolCount,
      };
    } else {
      const indexPath = path.join(skillDir, 'index.ts');
      config[name] = {
        command: 'npx',
        args: ['tsx', indexPath],
        enabled: true,
        source: 'local',
        autoGenerated: lumi.autoGenerated || false,
        generatedFrom: lumi.generatedFrom,
        description: pkg.description || lumi.description || name,
        toolCount: lumi.toolCount,
      };
    }

    this.saveConfig(config);
  }

  /** Run npm install in a skill directory (fire-and-forget, non-blocking) */
  private installDepsInDir(dir: string): void {
    exec('npm install --loglevel=error --no-audit --no-fund', {
      timeout: 120000,
      cwd: dir,
    }, (error, _stdout, stderr) => {
      if (error) {
        console.warn(`[MCP] npm install failed in ${dir}:`, stderr.trim() || error.message);
      } else {
        console.log(`[MCP] Dependencies installed in ${path.basename(dir)}`);
      }
    });
  }

  private copyDirSync(src: string, dest: string): void {
    if (!fs.existsSync(dest)) fs.mkdirSync(dest, { recursive: true });
    const entries = fs.readdirSync(src, { withFileTypes: true });
    for (const entry of entries) {
      const srcPath = path.join(src, entry.name);
      const destPath = path.join(dest, entry.name);
      if (entry.isDirectory()) {
        if (entry.name === 'node_modules') continue; // skip, will be installed by user
        this.copyDirSync(srcPath, destPath);
      } else {
        fs.copyFileSync(srcPath, destPath);
      }
    }
  }

  // ── MCP Server connection management ──

  async connectAll(): Promise<MCPToolDef[]> {
    // Scan local skills directory and register any unregistered skills
    this.ensureSkillsDir();
    const localEntries = fs.existsSync(SKILLS_DIR)
      ? fs.readdirSync(SKILLS_DIR, { withFileTypes: true })
      : [];
    const config = this.getConfig();

    for (const entry of localEntries) {
      if (!entry.isDirectory()) continue;
      const skillDir = path.join(SKILLS_DIR, entry.name);
      const indexPath = path.join(skillDir, 'index.ts');
      if (!fs.existsSync(indexPath)) continue;

      if (!config[entry.name]) {
        let pkg: any = {};
        try {
          pkg = JSON.parse(fs.readFileSync(path.join(skillDir, 'package.json'), 'utf-8'));
        } catch {}
        this.registerLocalSkill(entry.name, skillDir, pkg);
      }
    }

    // Reload config after auto-registering local skills
    const finalConfig = this.getConfig();
    const allTools: MCPToolDef[] = [];

    for (const [serverName, serverConfig] of Object.entries(finalConfig)) {
      if (!serverConfig.enabled) continue;

      try {
        const tools = await this.connectServer(serverName, serverConfig);
        allTools.push(...tools);

        // Update toolCount in config
        if (serverConfig.source === 'local' && serverConfig.toolCount !== tools.length) {
          serverConfig.toolCount = tools.length;
          this.saveConfig(finalConfig);
        }

        console.log(`[MCP] ${serverName}: ${tools.length} tools discovered (${serverConfig.source || 'external'})`);
      } catch (err: any) {
        console.warn(`[MCP] Failed to connect to ${serverName}: ${err.message}`);
      }
    }

    return allTools;
  }

  private async connectServer(name: string, config: MCPServerConfig): Promise<MCPToolDef[]> {
    const transportType = config.transport || (config.url ? (config.url.startsWith('wss://') || config.url.startsWith('ws://') ? 'ws' : 'http') : 'stdio');
    let transport: StdioClientTransport | StreamableHTTPClientTransport | WebSocketClientTransport;

    if (transportType === 'ws' && config.url) {
      transport = new WebSocketClientTransport(new URL(config.url));
    } else if (transportType === 'http' && config.url) {
      transport = new StreamableHTTPClientTransport(
        new URL(config.url),
        {
          requestInit: config.headers ? { headers: config.headers } : undefined,
        },
      );
    } else if (config.command) {
      transport = new StdioClientTransport({
        command: config.command,
        args: config.args || [],
        env: config.env || undefined,
      });
    } else {
      throw new Error(`MCP server "${name}": must provide "url" for http/ws transport or "command" for stdio transport`);
    }

    const client = new Client(
      { name: 'lumiOS-mcp-client', version: '2.0' },
      { capabilities: {} },
    );

    await client.connect(transport);

    this.servers.set(name, { client, transport, config });

    // Initialize crash tracker
    if (!this.crashTrackers.has(name)) {
      this.crashTrackers.set(name, {
        consecutiveCrashes: 0,
        lastCrashTime: '',
        lastSuccessfulConnect: new Date().toISOString(),
        restartTimer: null,
      });
    }

    // Install crash detection on transport
    const self = this;
    transport.onclose = () => {
      // If intentionally closing, skip crash detection
      if (self.closingSet.has(name)) {
        self.closingSet.delete(name);
        return;
      }
      // If server still in map, this is an unexpected crash
      if (self.servers.has(name)) {
        console.log(`[MCP] CRASH DETECTED: "${name}" process exited unexpectedly`);
        self.servers.delete(name);
        const tracker = self.crashTrackers.get(name);
        if (tracker) {
          tracker.lastCrashTime = new Date().toISOString();
        }
        self.scheduleRestart(name);
        self.broadcastHealth();
      }
    };

    transport.onerror = (error: Error) => {
      console.error(`[MCP] Error in "${name}" transport:`, error.message);
    };

    // Reset crash counter on successful connect
    const tracker = self.crashTrackers.get(name)!;
    tracker.consecutiveCrashes = 0;
    tracker.lastSuccessfulConnect = new Date().toISOString();
    if (tracker.restartTimer) {
      clearTimeout(tracker.restartTimer);
      tracker.restartTimer = null;
    }

    const result = await client.listTools();
    return result.tools.map((tool: any) => ({
      serverName: name,
      name: `mcp_${name}_${tool.name}`,
      description: tool.description || `${tool.name} (from MCP server: ${name})`,
      inputSchema: tool.inputSchema || { type: 'object', properties: {} },
    }));
  }

  async callTool(fullName: string, args: Record<string, any>): Promise<string> {
    const match = fullName.match(/^mcp_(.+?)_(.+)$/);
    if (!match) throw new Error(`Invalid MCP tool name: ${fullName}`);

    const [, serverName, toolName] = match;
    const server = this.servers.get(serverName);
    if (!server) throw new Error(`MCP server "${serverName}" not connected`);

    const result = await server.client.callTool({ name: toolName, arguments: args });

    const contents = (result as any).content || [];
    return contents
      .filter((c: any) => c.type === 'text')
      .map((c: any) => c.text)
      .join('\n');
  }

  async disconnectAll(): Promise<void> {
    // Cancel all pending restart timers
    for (const [n, tracker] of this.crashTrackers) {
      if (tracker.restartTimer) {
        clearTimeout(tracker.restartTimer);
        tracker.restartTimer = null;
      }
    }
    for (const [name, server] of this.servers) {
      this.closingSet.add(name);
      try {
        await server.transport.close();
      } catch {}
    }
    this.servers.clear();
    this.closingSet.clear();
  }

  async restartServer(name: string): Promise<MCPToolDef[]> {
    const server = this.servers.get(name);
    if (server) {
      this.closingSet.add(name);
      try { await server.transport.close(); } catch {}
      this.servers.delete(name);
      this.closingSet.delete(name);
    }

    const config = this.getConfig();
    const serverConfig = config[name];
    if (!serverConfig || !serverConfig.enabled) return [];

    return this.connectServer(name, serverConfig);
  }

  private scheduleRestart(name: string): void {
    const tracker = this.crashTrackers.get(name);
    if (!tracker) return;

    if (tracker.restartTimer) {
      clearTimeout(tracker.restartTimer);
    }

    // Max 5 consecutive crashes before giving up
    if (tracker.consecutiveCrashes >= 5) {
      console.error(`[MCP] "${name}" crashed ${tracker.consecutiveCrashes} times — giving up. Manual intervention required.`);
      return;
    }

    const delay = Math.min(1000 * Math.pow(2, tracker.consecutiveCrashes), 60000);
    tracker.consecutiveCrashes++;

    console.log(`[MCP] Scheduling restart for "${name}" in ${delay}ms (crash #${tracker.consecutiveCrashes})`);

    tracker.restartTimer = setTimeout(async () => {
      tracker.restartTimer = null;
      try {
        const config = this.getConfig();
        const serverConfig = config[name];
        if (!serverConfig || !serverConfig.enabled) {
          console.log(`[MCP] Server "${name}" is now disabled, skipping restart`);
          return;
        }

        const tools = await this.connectServer(name, serverConfig);
        console.log(`[MCP] "${name}" restarted successfully with ${tools.length} tools`);

        tracker.consecutiveCrashes = 0;
        tracker.lastSuccessfulConnect = new Date().toISOString();

        this.onServerRecovered?.(name, tools);
      } catch (err: any) {
        console.error(`[MCP] Restart attempt for "${name}" failed: ${err.message}`);
      }
      this.broadcastHealth();
    }, delay);
  }

  getServerHealth(): Record<string, { status: string; consecutiveCrashes: number; lastCrashTime?: string; lastSuccessfulConnect?: string }> {
    const config = this.getConfig();
    const health: Record<string, any> = {};
    for (const [name] of Object.entries(config)) {
      const tracker = this.crashTrackers.get(name);
      const isRestarting = !!tracker?.restartTimer;
      health[name] = {
        status: isRestarting ? 'restarting'
          : this.servers.has(name) ? 'connected'
          : (tracker?.consecutiveCrashes ?? 0) >= 5 ? 'failed'
          : (tracker?.consecutiveCrashes ?? 0) > 0 ? 'crashed'
          : 'disconnected',
        consecutiveCrashes: tracker?.consecutiveCrashes || 0,
        lastCrashTime: tracker?.lastCrashTime || undefined,
        lastSuccessfulConnect: tracker?.lastSuccessfulConnect || undefined,
      };
    }
    return health;
  }

  private broadcastHealth(): void {
    if (this.ioRef) {
      this.ioRef.emit('mcp:health_update', { servers: this.getServerHealth() });
    }
  }

  getConnectedServers(): string[] {
    return Array.from(this.servers.keys());
  }
}

export const mcpManager = new MCPClientManager();
export { SKILLS_DIR };
