import { Router, Request, Response, NextFunction } from "express";
import path from "path";
import fs from "fs";
import os from "os";
import { execSync } from "child_process";
import { readDB, writeDB } from "../../db_layer";
import { mcpManager, getMCPConfig, updateMCPConfig, SKILLS_DIR } from "../mcp";
import { generateSkill } from "../skills/generator";
import { getRecentWorkflows } from "../skills/worklog";

const asyncHandler = (fn: (req: Request, res: Response, next?: NextFunction) => Promise<any>) =>
  (req: Request, res: Response, next: NextFunction) =>
    Promise.resolve(fn(req, res, next)).catch(next);

export function mountSkillRoutes(
  router: Router,
  jwtSecret: string,
  llmGetters: {
    getDeepSeek: () => any;
    getGemini: () => any;
    getOpenAI?: () => any;
    getAnthropic?: () => any;
    getQwen?: () => any;
  },
  io: { emit: (event: string, data: any) => void },
) {
  // List all installed skills (local + external MCP servers)
  router.get("/skills", (req, res) => {
    try {
      const localSkills = mcpManager.listLocalSkills();
      const mcpConfig = getMCPConfig();
      const allSkills = Object.entries(mcpConfig).map(([name, config]) => {
        const local = localSkills.find(s => s.name === name);
        return {
          name,
          description: config.description || name,
          enabled: config.enabled,
          source: config.source || 'external',
          autoGenerated: config.autoGenerated || false,
          generatedFrom: config.generatedFrom,
          toolCount: config.toolCount || (local?.toolCount || 0),
          installedAt: local?.installedAt || '',
          connected: mcpManager.getConnectedServers().includes(name),
        };
      });
      res.json({ skills: allSkills });
    } catch (err: any) {
      res.status(500).json({ error: err.message });
    }
  });

  // Generate a skill from description or workflows
  router.post("/skills/generate", asyncHandler(async (req, res) => {
    try {
      const { description, provider, model } = req.body;

      let workflows;
      if (req.body.workflowIds) {
        const allWorkflows = getRecentWorkflows();
        workflows = allWorkflows.filter(w => (req.body.workflowIds as string[]).includes(w.id));
      } else if (req.body.useRecent) {
        workflows = getRecentWorkflows().slice(-5);
      }

      const result = await generateSkill(
        {
          description,
          workflows,
          provider: provider || 'deepseek',
          model: model || 'deepseek-chat',
          userId: (req as any).user?.uid || 'anonymous',
        },
        llmGetters.getDeepSeek, llmGetters.getGemini, llmGetters.getOpenAI, llmGetters.getAnthropic, llmGetters.getQwen,
      );

      if (result.success) {
        // Save generated skill code to knowledge base for agent ingestion
        try {
          const kbDir = path.join(process.cwd(), 'data', 'knowledge');
          fs.mkdirSync(kbDir, { recursive: true });
          const safeName = `skill-${result.skillName}.ts`;
          fs.writeFileSync(path.join(kbDir, safeName), result.generatedCode || '', 'utf-8');
          const db = readDB();
          if (!db.knowledgeFiles) db.knowledgeFiles = [];
          const existing = db.knowledgeFiles.find((m: any) => m.filename === safeName);
          if (existing) {
            existing.source = 'generated';
            existing.updatedAt = new Date().toISOString();
          } else {
            db.knowledgeFiles.push({
              filename: safeName,
              source: 'generated',
              agentIds: [],
              createdAt: new Date().toISOString(),
              updatedAt: new Date().toISOString(),
            });
          }
          writeDB(db);
        } catch (e) {
          console.warn('[SkillGen] Failed to save to knowledge base:', e);
        }
        io.emit('skill:updated', { name: result.skillName });
        res.json(result);
      } else {
        res.status(400).json(result);
      }
    } catch (err: any) {
      res.status(500).json({ error: err.message });
    }
  }));

  // Install a skill from git/npm/local
  router.post("/skills/install", async (req, res) => {
    try {
      const { source, url, package: pkgName, path: localPath, name } = req.body;

      if (source === 'git' && url) {
        const skillName = name || url.split('/').pop()?.replace('.git', '') || 'unnamed';
        const tmpDir = path.join(os.tmpdir(), `lumi_skill_${Date.now()}`);
        execSync(`git clone "${url}" "${tmpDir}"`, { stdio: 'pipe', timeout: 30000 });
        const destDir = mcpManager.installSkill(skillName, tmpDir);
        fs.rmSync(tmpDir, { recursive: true, force: true });

        // Restart to pick up new skill
        await mcpManager.restartServer(skillName);
        res.json({ success: true, name: skillName, directory: destDir });
      } else if (source === 'local' && localPath) {
        const skillName = name || path.basename(localPath);
        const destDir = mcpManager.installSkill(skillName, localPath);
        await mcpManager.restartServer(skillName);
        res.json({ success: true, name: skillName, directory: destDir });
      } else if (source === 'npm' && pkgName) {
        res.status(400).json({ error: 'npm install not yet implemented — use git URL instead' });
      } else {
        res.status(400).json({ error: 'Invalid source. Use: git (with url), local (with path), or npm (with package)' });
      }
    } catch (err: any) {
      res.status(500).json({ error: err.message });
    }
  });

  // Uninstall a skill
  router.delete("/skills/:name", async (req, res) => {
    try {
      mcpManager.uninstallSkill(req.params.name);
      io.emit('skill:uninstalled', { name: req.params.name });
      res.json({ success: true });
    } catch (err: any) {
      res.status(500).json({ error: err.message });
    }
  });

  // Enable a skill
  router.post("/skills/:name/enable", async (req, res) => {
    try {
      const config = getMCPConfig();
      if (!config[req.params.name]) return res.status(404).json({ error: 'Skill not found' });
      config[req.params.name].enabled = true;
      updateMCPConfig(config);
      res.json({ success: true });
    } catch (err: any) {
      res.status(500).json({ error: err.message });
    }
  });

  // Disable a skill
  router.post("/skills/:name/disable", async (req, res) => {
    try {
      const config = getMCPConfig();
      if (!config[req.params.name]) return res.status(404).json({ error: 'Skill not found' });
      config[req.params.name].enabled = false;
      updateMCPConfig(config);
      res.json({ success: true });
    } catch (err: any) {
      res.status(500).json({ error: err.message });
    }
  });

  // Workflow inspection (for debugging / manual generation)
  router.get("/skills/workflows", (req, res) => {
    const workflows = getRecentWorkflows((req as any).user?.uid);
    res.json({ workflows: workflows.slice(-20), total: workflows.length });
  });
}
