/**
 * Lumi Skill Generator — LLM-driven MCP server package generation.
 *
 * Takes workflow records (tool call sequences) or natural language descriptions
 * and generates a complete, installable MCP server package in ~/lumi_skills/.
 */
import fs from 'fs';
import path from 'path';
import os from 'os';
import { exec } from 'child_process';
import { makeLLMCall, NormalizedMessage } from '../llm/providers';
import { WorkflowRecord, WorkflowStep } from './worklog';
import { mcpManager, SKILLS_DIR } from '../mcp/client';
import { MCPServerConfig } from '../mcp/client';

const SKILLS_DIR_PATH = SKILLS_DIR;

export interface SkillGenerateRequest {
  /** Natural language description of what the skill should do */
  description?: string;
  /** Existing workflows to learn from */
  workflows?: WorkflowRecord[];
  /** LLM provider to use */
  provider?: 'deepseek' | 'qwen' | 'openai' | 'gemini' | 'anthropic';
  model?: string;
  userId?: string;
}

export interface SkillGenerateResult {
  success: boolean;
  skillName?: string;
  toolName?: string;
  directory?: string;
  error?: string;
  generatedCode?: string;
}

const GENERATE_PROMPT = `You are a Skill SDK generator for LumiOS. Your job is to create an MCP (Model Context Protocol) server tool with a fully implemented, executable handler function.

## Context
Lumi has learned a repeatable workflow by observing tool execution patterns. You need to encode this knowledge as a standalone MCP tool with REAL, EXECUTABLE code.

## Input
{inputDescription}

## Output Requirements
Output ONLY a JSON object with these fields:

{
  "skillName": "lowercase-kebab-case-name",
  "toolName": "snake_case_tool_name",
  "toolDescription": "1-2 sentence description of what this tool does",
  "inputSchema": {
    "type": "object",
    "properties": {
      "paramName": { "type": "string", "description": "what this param is" }
    },
    "required": ["paramName"]
  },
  "handlerCode": "The COMPLETE TypeScript body of the handler function. Write the code that goes INSIDE the async function body (NOT the function signature - just the body lines). You MUST set a variable named 'result' with the output string. Always wrap logic in try/catch, setting result to the error message on failure. The function has access to 'args' (Record<string, any>) with the destructured parameters. Use fetch() for HTTP calls, fs (imported as 'fs/promises') for file ops. Example:\\n  const {{ url }} = args;\\n  try {\\n    const response = await fetch(url);\\n    const data = await response.text();\\n    result = data.slice(0, 2000);\\n  } catch (e) {\\n    result = 'Error: ' + e.message;\\n  }",
  "readme": "Markdown documentation: what the skill does, usage example, parameters, output format"
}

## Guidelines
- The skillName should be short and descriptive (max 3 words, kebab-case)
- If the workflow involves web APIs, describe the exact endpoints and parameters in the handlerCode
- If using file operations, use 'fs/promises' (already imported) and specify file paths
- handlerCode MUST be real executable TypeScript, not a description. It runs in a Node.js child process.
- Keep inputSchema focused: only parameters that change between invocations
- Always set 'result' to a string before the function returns
- For async operations, use 'await' — the handler is an async function
- Do NOT include 'import' statements or 'export' — those are added automatically

JSON output:`;

const SKILL_TEMPLATE = `/**
 * Auto-generated Lumi Skill: {skillName}
 * Generated at: {timestamp}
 * Generator: Lumi Skill SDK
 */
import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js';
import { z } from 'zod';
import fs from 'fs/promises';

// ── Generated Handler ──
{handlerCode}

// ── Schema (generated) ──
const inputSchema = {inputSchema};

// ── MCP Server Entry ──
async function main() {
  const server = new McpServer(
    { name: '{skillName}', version: '1.0.0' },
    { capabilities: { tools: {} } }
  );

  server.registerTool(
    '{toolName}',
    {
      description: '{toolDescription}',
      inputSchema,
    },
    handler
  );

  const transport = new StdioServerTransport();
  await server.connect(transport);
  console.error('[Lumi Skill] {skillName} ready');
}

main().catch((err) => {
  console.error('[Lumi Skill] Fatal:', err);
  process.exit(1);
});
`;

const PACKAGE_TEMPLATE = `{
  "name": "lumi-skill-{skillName}",
  "version": "1.0.0",
  "description": "{toolDescription}",
  "type": "module",
  "main": "index.ts",
  "scripts": {
    "start": "npx tsx index.ts"
  },
  "dependencies": {
    "@modelcontextprotocol/sdk": "^1.0.0",
    "zod": "^3.22.0"
  },
  "lumi": {
    "autoGenerated": true,
    "generatedFrom": "{generatedFrom}",
    "installedAt": "{installedAt}",
    "toolCount": 1
  }
}
`;

/**
 * Generate a skill from workflow records or a natural language description.
 */
export async function generateSkill(
  request: SkillGenerateRequest,
  getDeepSeek: () => any,
  getGemini: () => any,
  getOpenAI?: () => any,
  getAnthropic?: () => any,
  getQwen?: () => any,
): Promise<SkillGenerateResult> {
  // Build input description for LLM
  let inputDescription = '';

  if (request.workflows && request.workflows.length > 0) {
    const intents = [...new Set(request.workflows.map(w => w.userIntent))];
    const allTools = request.workflows.flatMap(w => w.toolSequence);

    inputDescription = `## Observed Workflow Pattern
This workflow has been executed ${request.workflows.length} times.

### User Intent
${intents.join('\n')}

### Tool Call Sequences
${request.workflows.map((w, i) => `
Execution #${i + 1}:
${w.toolSequence.map((s, j) => `  ${j + 1}. ${s.name}(${JSON.stringify(s.args)}) → ${s.resultSummary.slice(0, 100)}`).join('\n')}
`).join('\n')}

### Most Common Tools Used
${topTools(allTools).map(t => `- ${t.name} (${t.count}x)`).join('\n')}
`;
  } else if (request.description) {
    inputDescription = `## User Request\n${request.description}`;
  } else {
    return { success: false, error: 'No workflows or description provided' };
  }

  const prompt = GENERATE_PROMPT.replace('{inputDescription}', inputDescription);

  const messages: NormalizedMessage[] = [
    { role: 'user', content: prompt },
  ];

  const provider = request.provider || 'deepseek';
  const model = request.model || 'deepseek-chat';

  try {
    const response = await makeLLMCall(
      messages,
      [],
      { provider, model, maxTokens: 2048, userId: request.userId || 'skill_gen' },
      getDeepSeek,
      getGemini,
      getOpenAI,
      getAnthropic,
      getQwen,
    );

    const text = response.text || '';
    const jsonMatch = text.match(/\{[\s\S]*\}/);
    if (!jsonMatch) {
      return { success: false, error: 'LLM did not return valid JSON', generatedCode: text };
    }

    const parsed = JSON.parse(jsonMatch[0]);

    if (!parsed.skillName || !parsed.toolName) {
      return { success: false, error: 'Missing skillName or toolName in generated output', generatedCode: text };
    }

    if (!parsed.handlerCode || typeof parsed.handlerCode !== 'string' || parsed.handlerCode.trim().length === 0) {
      // If LLM returned old field name (handlerLogic), retry with explicit conversion prompt
      if (parsed.handlerLogic && typeof parsed.handlerLogic === 'string') {
        console.warn('[SkillGen] LLM returned handlerLogic instead of handlerCode — retrying with conversion prompt');
        const conversionMessages: NormalizedMessage[] = [
          { role: 'user', content: `Turn this handler logic description into a TypeScript body for an async function handler(args). The function sets a variable named "result" to the output string. Use try/catch. You have access to 'args' (Record<string, any>), fetch(), and 'fs/promises' (imported as 'fs').\n\nLogic:\n${parsed.handlerLogic}\n\nReturn ONLY a JSON object: {"handlerCode": "// the executable code here"}` },
        ];
        try {
          const convResponse = await makeLLMCall(
            conversionMessages, [],
            { provider, model, maxTokens: 2048, userId: request.userId || 'skill_gen' },
            getDeepSeek, getGemini, getOpenAI, getAnthropic, getQwen,
          );
          const convText = convResponse.text || '';
          const convJson = convText.match(/\{[\s\S]*\}/);
          if (convJson) {
            const convParsed = JSON.parse(convJson[0]);
            if (convParsed.handlerCode && typeof convParsed.handlerCode === 'string') {
              parsed.handlerCode = convParsed.handlerCode;
              console.log('[SkillGen] Successfully converted handlerLogic → handlerCode');
            }
          }
        } catch (e: any) {
          console.warn('[SkillGen] handlerLogic conversion retry failed:', e.message);
        }
      }

      // If still no handlerCode after retry, fail
      if (!parsed.handlerCode || typeof parsed.handlerCode !== 'string' || parsed.handlerCode.trim().length === 0) {
        return { success: false, error: 'LLM did not return handlerCode', generatedCode: text };
      }
    }

    // Build the skill package
    const skillName = parsed.skillName.toLowerCase().replace(/[^a-z0-9-]/g, '-');
    const skillDir = path.join(SKILLS_DIR_PATH, skillName);
    const generatedFrom = request.workflows
      ? request.workflows.map(w => w.id).join(',')
      : 'manual';

    const now = new Date().toISOString();

    // Build the executable handler function from LLM-generated code
    const handlerCode = buildHandlerFunction(parsed.handlerCode, parsed.inputSchema);

    // Build the input schema as a Zod-compatible object literal for the template
    const schemaLiteral = buildSchemaLiteral(parsed.inputSchema);

    // Fill templates
    let indexTs = SKILL_TEMPLATE
      .replace(/{skillName}/g, skillName)
      .replace(/{toolName}/g, parsed.toolName)
      .replace(/{toolDescription}/g, (parsed.toolDescription || parsed.toolName).replace(/"/g, '\\"'))
      .replace(/{timestamp}/g, now)
      .replace('{handlerCode}', handlerCode)
      .replace('{inputSchema}', schemaLiteral);

    const packageJson = PACKAGE_TEMPLATE
      .replace(/{skillName}/g, skillName)
      .replace(/{toolDescription}/g, (parsed.toolDescription || '').replace(/"/g, '\\"'))
      .replace(/{generatedFrom}/g, generatedFrom)
      .replace(/{installedAt}/g, now);

    const readme = (parsed.readme || `# ${skillName}\n\n${parsed.toolDescription}`);

    // Write files
    if (!fs.existsSync(skillDir)) fs.mkdirSync(skillDir, { recursive: true });
    fs.writeFileSync(path.join(skillDir, 'package.json'), packageJson);
    fs.writeFileSync(path.join(skillDir, 'index.ts'), indexTs);
    fs.writeFileSync(path.join(skillDir, 'README.md'), readme);

    console.log(`[SkillGen] Generated skill "${skillName}" at ${skillDir}`);

    let warnings: string[] = [];

    // Install dependencies so the skill can actually run
    try {
      await installSkillDeps(skillDir);
      console.log(`[SkillGen] Dependencies installed for "${skillName}"`);
    } catch (e: any) {
      console.warn(`[SkillGen] npm install failed for "${skillName}":`, e.message);
      warnings.push(`npm install failed: ${e.message}`);
    }

    // Runtime smoke test — verify the process can start
    const runtimeCheck = await validateSkillRuntime(skillDir);
    if (!runtimeCheck.valid) {
      console.warn(`[SkillGen] Runtime check failed for "${skillName}":`, runtimeCheck.error);
      warnings.push(`Runtime check failed: ${runtimeCheck.error}`);
    }

    // Validate TypeScript compilation
    let validation = await validateSkillTypeScript(skillDir);

    if (!validation.valid) {
      console.warn(`[SkillGen] Type-check failed for "${skillName}", retrying with error feedback...`);
      warnings.push(`First attempt type errors: ${validation.errors.slice(0, 500)}`);

      // Retry: feed errors back to LLM
      const retryPrompt = `Fix the TypeScript errors in this handler code.

## Original description
${inputDescription}

## Errored handler code
${parsed.handlerCode}

## TypeScript errors
${validation.errors}

Return ONLY a JSON object with "handlerCode" (the fixed code body).`;

      try {
        const retryMessages: NormalizedMessage[] = [
          { role: 'user', content: retryPrompt },
        ];
        const retryResponse = await makeLLMCall(
          retryMessages, [],
          { provider, model, maxTokens: 2048, userId: request.userId || 'skill_gen' },
          getDeepSeek, getGemini, getOpenAI, getAnthropic, getQwen,
        );

        const retryText = retryResponse.text || '';
        const retryJson = retryText.match(/\{[\s\S]*\}/);
        if (retryJson) {
          const retryParsed = JSON.parse(retryJson[0]);
          const fixedCode = retryParsed.handlerCode;
          if (fixedCode && typeof fixedCode === 'string') {
            const fixedHandler = buildHandlerFunction(fixedCode, parsed.inputSchema);
            const fixedIndexTs = SKILL_TEMPLATE
              .replace(/{skillName}/g, skillName)
              .replace(/{toolName}/g, parsed.toolName)
              .replace(/{toolDescription}/g, (parsed.toolDescription || parsed.toolName).replace(/"/g, '\\"'))
              .replace(/{timestamp}/g, now)
              .replace('{handlerCode}', fixedHandler)
              .replace('{inputSchema}', schemaLiteral);

            fs.writeFileSync(path.join(skillDir, 'index.ts'), fixedIndexTs);

            validation = await validateSkillTypeScript(skillDir);
            if (validation.valid) {
              console.log(`[SkillGen] Type-check passed after retry for "${skillName}"`);
              warnings = [];
              // Use the fixed code in the return
              indexTs = fixedIndexTs;

              // Install deps for the corrected skill
              try {
                await installSkillDeps(skillDir);
              } catch (e: any) {
                console.warn(`[SkillGen] npm install failed after retry for "${skillName}":`, e.message);
                warnings.push(`npm install failed: ${e.message}`);
              }

              // Runtime smoke test on the fixed code
              const rtCheck = await validateSkillRuntime(skillDir);
              if (!rtCheck.valid) {
                warnings.push(`Runtime check after retry: ${rtCheck.error}`);
              }
            } else {
              warnings.push(`Retry still failing: ${validation.errors.slice(0, 300)}`);
              console.warn(`[SkillGen] Type-check still failing after retry for "${skillName}":`, validation.errors.slice(0, 200));
            }
          }
        }
      } catch (retryErr: any) {
        warnings.push(`Retry failed: ${retryErr.message}`);
      }
    }

    return {
      success: true,
      skillName,
      toolName: parsed.toolName,
      directory: skillDir,
      generatedCode: indexTs,
      ...(warnings.length > 0 ? { error: warnings.join(' | ') } : {}),
    };
  } catch (err: any) {
    console.error('[SkillGen] Generation failed:', err);
    return { success: false, error: err.message };
  }
}

/**
 * Auto-detect repeatable patterns in recent workflows and trigger generation.
 * Returns the generated skill info if a pattern was found and a skill was created.
 */
export async function autoGenerateSkill(
  getDeepSeek: () => any,
  getGemini: () => any,
  getOpenAI?: () => any,
  getAnthropic?: () => any,
  getQwen?: () => any,
): Promise<SkillGenerateResult | null> {
  const { findWorkflowClusters, getRecentWorkflows, removeWorkflows } = await import('./worklog');

  const all = getRecentWorkflows();
  if (all.length < 3) return null;

  const clusters = findWorkflowClusters(3);
  if (clusters.length === 0) return null;

  for (const cluster of clusters) {
    console.log(
      `[SkillGen] Auto-detected cluster: "${cluster.representativeIntent.slice(0, 40)}" ` +
      `(${cluster.workflows.length}x, avg similarity: ${cluster.avgSimilarity.toFixed(2)})`,
    );
    const result = await generateSkill(
      { workflows: cluster.workflows, provider: 'deepseek', model: 'deepseek-chat' },
      getDeepSeek, getGemini, getOpenAI, getAnthropic, getQwen,
    );

    if (result.success && result.skillName) {
      // Install the generated skill
      try {
        mcpManager.installSkill(result.skillName, result.directory!);
        console.log(`[SkillGen] Auto-installed skill "${result.skillName}"`);
        // Clear processed workflows so they don't re-trigger
        removeWorkflows(cluster.workflows.map(w => w.id));
      } catch (err: any) {
        console.warn(`[SkillGen] Auto-install failed: ${err.message}`);
      }

      return result;
    }
  }

  return null;
}

// ── Validation ──

async function validateSkillTypeScript(skillDir: string): Promise<{ valid: boolean; errors: string }> {
  return new Promise((resolve) => {
    exec('npx tsc --noEmit', {
      timeout: 60000,
      maxBuffer: 512 * 1024,
      cwd: skillDir,
    }, (error, stdout, stderr) => {
      const output = (stdout + '\n' + stderr).trim();
      if (!error && !output) {
        resolve({ valid: true, errors: '' });
      } else {
        resolve({ valid: false, errors: output || error?.message || 'Unknown error' });
      }
    });
  });
}

/** Install npm dependencies in the skill directory so it can actually run */
async function installSkillDeps(skillDir: string): Promise<void> {
  return new Promise((resolve, reject) => {
    exec('npm install --loglevel=error --no-audit --no-fund', {
      timeout: 120000,
      maxBuffer: 512 * 1024,
      cwd: skillDir,
    }, (error, _stdout, stderr) => {
      if (error) {
        reject(new Error(stderr.trim() || error.message));
      } else {
        resolve();
      }
    });
  });
}

/** Quick runtime smoke test: run the skill process briefly to verify it starts */
async function validateSkillRuntime(skillDir: string): Promise<{ valid: boolean; error?: string }> {
  return new Promise((resolve) => {
    const child = exec(
      'npx tsx index.ts',
      { timeout: 15000, cwd: skillDir, env: { ...process.env, LUMI_SKILL_SMOKE_TEST: '1' } },
      (_error, _stdout, stderr) => {
        // Process will exit quickly (or be killed) — success = no fatal crash
        const fatalPatterns = ['ERR_MODULE_NOT_FOUND', 'Cannot find package', 'SyntaxError', 'TypeError:'];
        const hasFatal = fatalPatterns.some(p => (stderr || '').includes(p));
        if (hasFatal) {
          resolve({ valid: false, error: (stderr || '').slice(0, 500) });
        } else {
          resolve({ valid: true });
        }
      },
    );
    // Kill after 5s — if it hasn't crashed by then, it successfully loaded
    setTimeout(() => {
      child.kill('SIGTERM');
      resolve({ valid: true });
    }, 5000);
  });
}

// ── Helpers ──

function topTools(steps: WorkflowStep[]): { name: string; count: number }[] {
  const counts: Record<string, number> = {};
  for (const s of steps) {
    counts[s.name] = (counts[s.name] || 0) + 1;
  }
  return Object.entries(counts)
    .sort((a, b) => b[1] - a[1])
    .slice(0, 5)
    .map(([name, count]) => ({ name, count }));
}

function buildHandlerFunction(handlerCode: string, inputSchema: any): string {
  const props = inputSchema?.properties || {};
  const paramNames = Object.keys(props);

  const destructure = paramNames.length > 0
    ? `  const { ${paramNames.join(', ')} } = args;`
    : '  // No parameters defined';

  // Indent the LLM-generated body code to match the function body
  const indentedBody = handlerCode
    .split('\n')
    .map(line => line.trim() ? `  ${line}` : '')
    .join('\n');

  return `async function handler(args: Record<string, any>): Promise<{ content: Array<{ type: 'text'; text: string }> }> {
${destructure}

  // ── Generated implementation ──
${indentedBody}

  return {
    content: [{ type: 'text', text: result }],
  };
}`;
}

function buildSchemaLiteral(schema: any): string {
  if (!schema || !schema.properties) {
    return '{ type: "object", properties: {}, required: [] }';
  }

  const props = schema.properties || {};
  const required = schema.required || [];

  const propEntries = Object.entries(props).map(([key, prop]: [string, any]) => {
    return `  ${key}: z.${mapJsonTypeToZod(prop.type || 'string')}()${prop.description ? `.describe('${prop.description.replace(/'/g, "\\'")}')` : ''}`;
  });

  if (propEntries.length === 0) {
    return `z.object({})`;
  }

  return `z.object({\n${propEntries.join(',\n')}\n})`;
}

function mapJsonTypeToZod(jsonType: string): string {
  switch (jsonType) {
    case 'string': return 'string';
    case 'number': return 'number';
    case 'integer': return 'number';
    case 'boolean': return 'boolean';
    case 'array': return 'array(z.any())';
    case 'object': return 'object({})';
    default: return 'string';
  }
}
