import React, { useState, useEffect } from 'react';
import { Cpu, RefreshCw, CheckCircle, XCircle, Wrench, Sparkles, Download, Plus, Search, Star, ExternalLink, AlertTriangle, XOctagon } from 'lucide-react';
import { Button } from './ui/button';
import { Input } from './ui/input';
import { toast } from 'sonner';
import { socketService } from '@/services/socketService';

interface MCPServer {
  name: string;
  command: string;
  args: string[];
  enabled: boolean;
  connected: boolean;
  source?: 'local' | 'external';
  autoGenerated?: boolean;
  toolCount?: number;
  description?: string;
}

interface ServerHealth {
  status: 'connected' | 'restarting' | 'crashed' | 'failed' | 'disconnected';
  consecutiveCrashes: number;
  lastCrashTime?: string;
  lastSuccessfulConnect?: string;
}

type HealthMap = Record<string, ServerHealth>;

export function MCPSettings({ t }: { t?: any }) {
  const [servers, setServers] = useState<MCPServer[]>([]);
  const [loading, setLoading] = useState(true);

  const fetchServers = async () => {
    try {
      // Use /api/skills which has richer metadata (source, autoGenerated, etc.)
      const res = await fetch('/api/skills');
      const data = await res.json();
      // Map skills into MCPServer-compatible shape
      const mapped = (data.skills || []).map((s: any) => ({
        name: s.name,
        command: 'npx',
        args: s.source === 'local' ? ['tsx', `~/gaea_skills/${s.name}/index.ts`] : [],
        enabled: s.enabled,
        connected: s.connected,
        source: s.source,
        autoGenerated: s.autoGenerated,
        toolCount: s.toolCount,
        description: s.description,
      }));
      setServers(mapped);
    } catch {
      // Fallback to traditional MCP endpoint
      try {
        const res = await fetch('/api/mcp');
        const data = await res.json();
        setServers(data.servers || []);
      } catch {
        // MCP endpoint unavailable
      }
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => { fetchServers(); }, []);

  const [healthMap, setHealthMap] = useState<HealthMap>({});

  const fetchHealth = async () => {
    try {
      const res = await fetch('/api/mcp/health');
      if (res.ok) {
        const data = await res.json();
        setHealthMap(data.servers || {});
      }
    } catch { /* health endpoint unavailable */ }
  };

  useEffect(() => { fetchHealth(); }, []);

  useEffect(() => {
    const s = socketService.getSocket();
    if (!s) return;
    const handler = (data: { servers: HealthMap }) => {
      setHealthMap(data.servers || {});
    };
    s.on('mcp:health_update', handler);
    return () => { s.off('mcp:health_update', handler); };
  }, []);

  // Add Server form
  const [showAddForm, setShowAddForm] = useState(false);
  const [newName, setNewName] = useState('');
  const [newCommand, setNewCommand] = useState('npx');
  const [newArgs, setNewArgs] = useState('');

  // GitHub search
  const [ghQuery, setGhQuery] = useState('');
  const [ghResults, setGhResults] = useState<any[]>([]);
  const [ghSearching, setGhSearching] = useState(false);
  const [ghSearched, setGhSearched] = useState(false);

  const handleAddServer = async () => {
    if (!newName.trim() || !newCommand.trim()) {
      toast.error(t?.mcpNameCommandRequired || 'Name and command are required');
      return;
    }
    const args = newArgs.trim() ? newArgs.split(/\s+/) : [];
    const payload = { [newName.trim()]: { command: newCommand.trim(), args, enabled: true } };
    try {
      const res = await fetch('/api/mcp', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ servers: payload }),
      });
      await res.json();
      toast.success(`${t?.mcpServerAdded || 'Server added'}: "${newName.trim()}"`);
      setNewName(''); setNewCommand('npx'); setNewArgs('');
      setShowAddForm(false);
      fetchServers();
    } catch (err: any) {
      toast.error(`${t?.mcpFailedToAddServer || 'Failed to add server'}: ${err.message}`);
    }
  };

  const handleGitHubSearch = async () => {
    if (!ghQuery.trim()) return;
    setGhSearching(true);
    setGhSearched(true);
    try {
      const res = await fetch(`/api/mcp/github/search?q=${encodeURIComponent(ghQuery.trim())}`);
      const data = await res.json();
      setGhResults(data.results || []);
    } catch {
      toast.error(t?.mcpSearchFailed || 'GitHub search failed');
    } finally {
      setGhSearching(false);
    }
  };

  const handleInstallFromGitHub = async (repo: string) => {
    try {
      const res = await fetch('/api/mcp', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ servers: { [repo]: { command: 'npx', args: ['-y', repo], enabled: true } } }),
      });
      await res.json();
      toast.success(`${t?.mcpInstalling || 'Installing'} ${repo}...`);
      fetchServers();
    } catch (err: any) {
      toast.error(`${t?.mcpInstallFailed || 'Install failed'}: ${err.message}`);
    }
  };

  const toggleServer = async (name: string, enabled: boolean) => {
    const updated = servers.map(s => s.name === name ? { ...s, enabled } : s);
    setServers(updated);

    const payload: Record<string, any> = {};
    for (const s of updated) {
      payload[s.name] = { command: s.command, args: s.args, enabled: s.enabled };
    }

    try {
      const res = await fetch('/api/mcp', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ servers: payload }),
      });
      const data = await res.json();
      toast.success(`${data.count} ${t?.mcpToolsRegistered || 'tools registered'}`);
      fetchServers();
    } catch (err: any) {
      toast.error(`${t?.mcpUpdateFailed || 'MCP update failed'}: ${err.message}`);
      fetchServers();
    }
  };

  const restartServer = async (name: string) => {
    try {
      const res = await fetch(`/api/mcp/restart/${name}`, { method: 'POST' });
      const data = await res.json();
      toast.success(`${data.tools?.length || 0} ${t?.mcpToolsReconnected || 'tools reconnected'}`);
      fetchServers();
    } catch (err: any) {
      toast.error(`${t?.mcpRestartFailed || 'Restart failed'}: ${err.message}`);
    }
  };

  if (loading) {
    return (
      <div className="space-y-8 animate-in fade-in duration-500">
        <div className="flex items-center gap-3">
          <Cpu className="text-celestial-saturn" />
          <h3 className="text-xl font-bold uppercase tracking-tighter text-white/90">{t?.mcpServers || 'MCP Servers'}</h3>
        </div>
        <p className="text-white/40 text-sm">{t?.mcpScanning || 'Scanning for MCP protocol servers...'}</p>
      </div>
    );
  }

  return (
    <div className="space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-500">
      <div className="flex items-center gap-3">
        <Cpu className="text-celestial-saturn" />
        <h3 className="text-xl font-bold uppercase tracking-tighter text-white/90">{t?.mcpServers || 'MCP Servers'}</h3>
      </div>

      <p className="text-sm text-white/40 max-w-xl">
        {t?.mcpDescription || "Model Context Protocol servers extend Gaea's capabilities. Auto-generated skills appear here alongside community-maintained servers."}
      </p>

      {servers.length === 0 ? (
        <div className="p-10 bg-white/5 rounded-[2rem] border border-white/5 text-center">
          <Wrench size={32} className="text-white/45 mx-auto mb-4" />
          <p className="text-white/40 font-bold uppercase tracking-widest text-sm">{t?.mcpNoServers || 'No MCP servers configured'}</p>
          <p className="text-white/45 text-xs mt-2">{t?.mcpAddHint || 'Add servers to server/mcp/config.json'}</p>
        </div>
      ) : (
        <div className="space-y-4">
          {servers.map(server => (
            <div
              key={server.name}
              className="p-6 bg-white/5 rounded-3xl border border-white/5 space-y-4 hover:border-white/10 transition-all"
            >
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-4">
                  {(() => {
                    const h = healthMap[server.name];
                    const status = h?.status || (server.connected ? 'connected' : 'disconnected');
                    const icon = status === 'connected' ? <CheckCircle size={20} />
                      : status === 'restarting' ? <RefreshCw size={20} className="animate-spin" />
                      : status === 'crashed' ? <AlertTriangle size={20} />
                      : status === 'failed' ? <XOctagon size={20} />
                      : <XCircle size={20} />;
                    const bg = status === 'connected' ? 'bg-green-500/10 text-green-500'
                      : status === 'restarting' ? 'bg-amber-500/10 text-amber-400'
                      : status === 'crashed' ? 'bg-red-500/10 text-red-400'
                      : status === 'failed' ? 'bg-red-500/10 text-red-400'
                      : 'bg-white/5 text-white/45';
                    return <div className={`w-10 h-10 rounded-xl flex items-center justify-center ${bg}`}>{icon}</div>;
                  })()}
                  <div>
                    <div className="flex items-center gap-2 flex-wrap">
                      <h4 className="font-bold text-white text-sm uppercase tracking-tight">{server.name}</h4>
                      {server.autoGenerated && (
                        <span className="text-xs px-1.5 py-0.5 bg-emerald-500/20 text-emerald-300 border border-emerald-500/30 rounded-full font-bold uppercase flex items-center gap-1">
                          <Sparkles size={8} /> {t?.mcpAutoGenerated || 'Auto-generated'}
                        </span>
                      )}
                      {server.source === 'local' && !server.autoGenerated && (
                        <span className="text-xs px-1.5 py-0.5 bg-sky-500/20 text-sky-300 border border-sky-500/30 rounded-full font-bold uppercase flex items-center gap-1">
                          <Download size={8} /> {t?.mcpInstalled || 'Installed'}
                        </span>
                      )}
                      {server.toolCount != null && (
                        <span className="text-[12px] text-white/45">{server.toolCount} tools</span>
                      )}
                    </div>
                    <p className="text-xs text-white/55 font-mono">{server.command} {server.args.join(' ')}</p>
                    {server.description && (
                      <p className="text-xs text-white/55 mt-1">{server.description}</p>
                    )}
                  </div>
                </div>

                <div className="flex items-center gap-3">
                  {server.enabled && (
                    <Button
                      onClick={() => restartServer(server.name)}
                      className="bg-white/5 hover:bg-white/10 border border-white/10 text-xs font-black uppercase tracking-widest px-3 h-9 rounded-xl"
                    >
                      <RefreshCw size={14} className="mr-1" />
                      {t?.mcpRestart || 'Restart'}
                    </Button>
                  )}
                  <button
                    onClick={() => toggleServer(server.name, !server.enabled)}
                    className={`w-10 h-5 rounded-full p-1 transition-colors cursor-pointer ${
                      server.enabled ? 'bg-celestial-saturn' : 'bg-white/10'
                    }`}
                  >
                    <div className={`w-3 h-3 rounded-full bg-white transition-transform ${
                      server.enabled ? 'translate-x-5' : 'translate-x-0'
                    }`} />
                  </button>
                </div>
              </div>

              {(() => {
                const h = healthMap[server.name];
                const status = h?.status || (server.connected ? 'connected' : 'disconnected');
                const crashes = h?.consecutiveCrashes || 0;
                const statusLabel =
                  status === 'connected' ? (t?.mcpConnected || '已连接')
                  : status === 'restarting' ? (t?.mcpRestarting || `重启中${crashes > 0 ? ` (第${crashes}次)` : ''}`)
                  : status === 'crashed' ? (t?.mcpCrashed || `已崩溃 (${crashes}次)`)
                  : status === 'failed' ? (t?.mcpFailed || `已放弃 (${crashes}次失败)`)
                  : t?.mcpDisconnected || '未连接';
                const dotColor =
                  status === 'connected' ? 'bg-green-500'
                  : status === 'restarting' ? 'bg-amber-400'
                  : status === 'crashed' ? 'bg-red-500'
                  : status === 'failed' ? 'bg-red-600'
                  : 'bg-white/20';
                const dotAnim = status === 'connected' || status === 'restarting' ? 'animate-pulse' : '';
                const textColor =
                  status === 'connected' ? 'text-green-500'
                  : status === 'restarting' ? 'text-amber-400'
                  : status === 'crashed' || status === 'failed' ? 'text-red-400'
                  : 'text-white/45';
                return (
                  <div className="flex items-center gap-2 text-xs font-bold uppercase tracking-widest">
                    <div className={`w-1.5 h-1.5 rounded-full ${dotColor} ${dotAnim}`} />
                    <span className={textColor}>{statusLabel}</span>
                    {h?.lastCrashTime && status !== 'connected' && (
                      <span className="text-white/40 font-mono normal-case text-[12px]">
                        {new Date(h.lastCrashTime).toLocaleTimeString()}
                      </span>
                    )}
                  </div>
                );
              })()}
            </div>
          ))}
        </div>
      )}

      {/* Add Server */}
      <div className="p-6 glass-dark rounded-[2rem] border border-white/5 space-y-4">
        <button
          onClick={() => setShowAddForm(!showAddForm)}
          className="flex items-center gap-3 w-full text-left"
        >
          <Plus className="text-celestial-saturn" size={18} />
          <h4 className="text-sm font-bold uppercase tracking-tight text-white">{t?.mcpAddServerTitle || 'Add MCP Server'}</h4>
        </button>
        {showAddForm && (
          <div className="space-y-3 pt-2">
            <div className="grid grid-cols-3 gap-3">
              <Input
                value={newName}
                onChange={e => setNewName(e.target.value)}
                placeholder={t?.mcpServerNamePlaceholder || 'Server name'}
                className="bg-white/5 border-white/10 rounded-xl py-2 text-sm"
                onKeyDown={e => e.key === 'Enter' && handleAddServer()}
              />
              <Input
                value={newCommand}
                onChange={e => setNewCommand(e.target.value)}
                placeholder={t?.mcpCommandPlaceholder || 'Command (npx, node, python...)'}
                className="bg-white/5 border-white/10 rounded-xl py-2 text-sm"
                onKeyDown={e => e.key === 'Enter' && handleAddServer()}
              />
              <Input
                value={newArgs}
                onChange={e => setNewArgs(e.target.value)}
                placeholder={t?.mcpArgsPlaceholder || 'Args (space-separated)'}
                className="bg-white/5 border-white/10 rounded-xl py-2 text-sm"
                onKeyDown={e => e.key === 'Enter' && handleAddServer()}
              />
            </div>
            <Button
              onClick={handleAddServer}
              disabled={!newName.trim() || !newCommand.trim()}
              className="bg-celestial-saturn text-black font-bold text-xs px-6 py-2 rounded-xl hover:scale-105 transition-transform disabled:opacity-40"
            >
              <Plus size={14} className="mr-1" /> {t?.mcpAddServerBtn || 'Add Server'}
            </Button>
          </div>
        )}
      </div>

      {/* GitHub Search */}
      <div className="p-6 glass-dark rounded-[2rem] border border-white/5 space-y-4">
        <div className="flex items-center gap-3">
          <Search className="text-celestial-saturn" size={18} />
          <h4 className="text-sm font-bold uppercase tracking-tight text-white">{t?.mcpSearchGitHubTitle || 'Search GitHub for MCP Servers'}</h4>
        </div>
        <div className="flex gap-3">
          <Input
            value={ghQuery}
            onChange={e => setGhQuery(e.target.value)}
            placeholder={t?.mcpSearchPlaceholder || 'Search MCP servers on GitHub...'}
            className="flex-1 bg-white/5 border-white/10 rounded-xl py-2 text-sm"
            onKeyDown={e => e.key === 'Enter' && handleGitHubSearch()}
          />
          <Button
            onClick={handleGitHubSearch}
            disabled={ghSearching || !ghQuery.trim()}
            className="bg-white/5 hover:bg-white/10 border border-white/10 text-xs font-black uppercase tracking-widest px-4 h-10 rounded-xl"
          >
            {ghSearching ? (t?.mcpSearching || 'Searching...') : (t?.mcpSearchBtn || 'Search')}
          </Button>
        </div>
        {ghSearched && ghResults.length === 0 && !ghSearching && (
          <p className="text-xs text-white/55">{t?.mcpNoResultsFound || 'No results found for'} "{ghQuery}"</p>
        )}
        {ghResults.length > 0 && (
          <div className="space-y-2 max-h-64 overflow-y-auto custom-scrollbar">
            {ghResults.map((repo: any) => (
              <div key={repo.id} className="flex items-center justify-between p-3 bg-white/5 rounded-xl border border-white/5 hover:border-white/10 transition-all">
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-2">
                    <span className="text-sm font-bold text-white/80 truncate">{repo.name}</span>
                    <a href={repo.url} target="_blank" rel="noopener noreferrer" className="text-white/45 hover:text-white/60">
                      <ExternalLink size={12} />
                    </a>
                  </div>
                  <p className="text-xs text-white/55 truncate mt-0.5">{repo.description || (t?.mcpNoDescription || 'No description')}</p>
                  <div className="flex items-center gap-3 mt-1">
                    <span className="text-[12px] text-white/45 flex items-center gap-1"><Star size={10} /> {repo.stars || 0}</span>
                    {repo.language && <span className="text-[12px] text-white/45">{repo.language}</span>}
                  </div>
                </div>
                <Button
                  onClick={() => handleInstallFromGitHub(repo.name)}
                  className="ml-3 bg-white/5 hover:bg-white/10 border border-white/10 text-xs font-black uppercase tracking-widest px-3 h-8 rounded-xl flex-shrink-0"
                >
                  <Download size={12} className="mr-1" /> {t?.mcpInstall || 'Install'}
                </Button>
              </div>
            ))}
          </div>
        )}
      </div>

      <div className="p-6 glass-dark rounded-[2rem] border border-white/5 space-y-4">
        <div className="flex items-center gap-3">
          <Wrench className="text-celestial-saturn" size={18} />
          <h4 className="text-sm font-bold uppercase tracking-tight text-white">{t?.mcpAvailableServers || 'Available MCP Servers'}</h4>
        </div>
        <p className="text-xs text-white/55 leading-relaxed">
          {t?.mcpInstallHint || 'Install MCP servers via npm or edit server/mcp/config.json to add new servers.'}
        </p>
      </div>
    </div>
  );
}
