import React, { useState, useEffect, useCallback } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { Sparkles, ShoppingBag, Cpu, Download, Trash2, Power, PowerOff, RefreshCw, Star, Wrench, CheckCircle, Globe, Search, Zap, Tag, ChevronDown, Upload, Palette, Terminal, Monitor, Film, Key, Users, ExternalLink } from 'lucide-react';
import { Button } from './ui/button';
import { Input } from './ui/input';
import { toast } from 'sonner';
import { useSocket } from '@/hooks/useSocket';

const ICON_CLASSES: Record<string, string> = {
  CloudSun: 'bg-sky-500/10 text-sky-400 border-sky-500/20',
  Languages: 'bg-violet-500/10 text-violet-400 border-violet-500/20',
  Calculator: 'bg-amber-500/10 text-amber-400 border-amber-500/20',
  StickyNote: 'bg-rose-500/10 text-rose-400 border-rose-500/20',
  Timer: 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20',
  Globe: 'bg-blue-500/10 text-blue-400 border-blue-500/20',
  Mail: 'bg-teal-500/10 text-teal-400 border-teal-500/20',
  QrCode: 'bg-indigo-500/10 text-indigo-400 border-indigo-500/20',
  Key: 'bg-yellow-500/10 text-yellow-400 border-yellow-500/20',
  Link: 'bg-cyan-500/10 text-cyan-400 border-cyan-500/20',
  Image: 'bg-pink-500/10 text-pink-400 border-pink-500/20',
  FileText: 'bg-orange-500/10 text-orange-400 border-orange-500/20',
  Palette: 'bg-purple-500/10 text-purple-400 border-purple-500/20',
  Sparkles: 'bg-amber-500/10 text-amber-400 border-amber-500/20',
  Terminal: 'bg-green-500/10 text-green-400 border-green-500/20',
  Monitor: 'bg-cyan-500/10 text-cyan-400 border-cyan-500/20',
  Search: 'bg-indigo-500/10 text-indigo-400 border-indigo-500/20',
  Film: 'bg-rose-500/10 text-rose-400 border-rose-500/20',
};

const ICON_COMPONENTS: Record<string, React.ReactNode> = {
  Globe: <Globe size={18} />,
  Sparkles: <Sparkles size={18} />,
  Terminal: <Terminal size={18} />,
  Monitor: <Monitor size={18} />,
  Search: <Search size={18} />,
  Palette: <Palette size={18} />,
  Film: <Film size={18} />,
  Zap: <Zap size={18} />,
};

interface MarketplaceSkill {
  id: string; name: string; description: string; author: string;
  downloads: number; rating: number; category: string; icon: string;
  installSource?: 'bundled' | 'community' | 'npm' | 'github'; installPath?: string; installed: boolean;
  version?: string; toolCount?: number;
  requiresApiKey?: boolean; apiKeyEnv?: string; apiKeyUrl?: string;
  requiresSetup?: boolean; setupNote?: string;
  npmPackage?: string; repoUrl?: string;
  runtime?: 'internal' | 'external'; externalCommand?: string;
}

interface InstalledSkill {
  name: string; description: string; enabled: boolean; source: string;
  autoGenerated: boolean; toolCount: number; installedAt: string; connected: boolean;
}

/** Normalized external result from npm or GitHub */
interface ExternalResult {
  id: string; name: string; description: string; author: string;
  installSource: 'npm' | 'github'; source: string;
  version?: string; stars?: number; url?: string; language?: string;
  npmPackage?: string; repoUrl?: string;
}

type Tab = 'featured' | 'marketplace' | 'installed' | 'generate';
type SortKey = 'downloads' | 'rating' | 'newest';

const FEATURED_SKILLS = [
  { id: 'pixelle', name: 'Pixelle Studio', icon: 'Palette', iconColor: 'from-purple-500 to-pink-500', desc: 'ComfyUI-powered AIGC studio. Text-to-image, image-to-video, sound generation — any ComfyUI workflow becomes an AI tool.', prompt: '帮我生成一张星空下的赛博朋克城市图片' },
  { id: 'minimax', name: 'MiniMax Studio', icon: 'Sparkles', iconColor: 'from-amber-400 to-yellow-500', desc: 'Multimodal creative powerhouse. Music generation, video creation, image synthesis, TTS, and voice cloning in one skill.', prompt: '帮我创作一首舒缓的钢琴曲，带有海浪的声音' },
  { id: 'desktop-automation', name: 'Desktop Commander', icon: 'Monitor', iconColor: 'from-cyan-500 to-blue-500', desc: 'Full desktop control. Mouse, keyboard, windows, and OCR screen reading — Gaea can see and operate your desktop.', prompt: '帮我把桌面上的文件按日期整理到文件夹里' },
  { id: 'video-editor', name: 'Video Forge', icon: 'Film', iconColor: 'from-rose-500 to-orange-500', desc: 'Video & audio editing suite. Trim, merge, crop, rotate, effects, overlays, and audio extraction via natural language.', prompt: '帮我把这个视频裁剪掉前30秒并加上字幕' },
  { id: 'fetcher', name: 'Web Fetcher Pro', icon: 'Globe', iconColor: 'from-blue-500 to-cyan-400', desc: 'Smart web content fetching. Converts any URL into clean, readable Markdown using Playwright + Readability.', prompt: '帮我抓取这篇文章的内容并总结要点' },
  { id: 'code-sandbox', name: 'Code Sandbox', icon: 'Terminal', iconColor: 'from-green-500 to-emerald-400', desc: 'Secure cloud code execution. Run Python and JavaScript in isolated containers — safe, fast, unlimited.', prompt: '帮我写一段Python代码分析CSV数据并生成图表' },
];

export function SkillCenter({ t, lang }: { t: any; lang: 'en' | 'zh' }) {
  const [activeTab, setActiveTab] = useState<Tab>('featured');
  const [marketSkills, setMarketSkills] = useState<MarketplaceSkill[]>([]);
  const [installedSkills, setInstalledSkills] = useState<InstalledSkill[]>([]);
  const [categories, setCategories] = useState<string[]>([]);
  const [loading, setLoading] = useState(true);
  const [installing, setInstalling] = useState<string | null>(null);
  const [search, setSearch] = useState('');
  const [activeCategory, setActiveCategory] = useState<string>('');
  const [sortKey, setSortKey] = useState<SortKey>('downloads');
  const [genDescription, setGenDescription] = useState('');
  const [generating, setGenerating] = useState(false);
  const [npmResults, setNpmResults] = useState<ExternalResult[]>([]);
  const [githubResults, setGithubResults] = useState<ExternalResult[]>([]);
  const [searchingExternal, setSearchingExternal] = useState(false);
  const [externalError, setExternalError] = useState('');
  const [installProgress, setInstallProgress] = useState<{ skillId: string; stage: string } | null>(null);
  const [detailSkill, setDetailSkill] = useState<MarketplaceSkill | InstalledSkill | null>(null);
  const [savedKeys, setSavedKeys] = useState<Record<string, boolean>>({});
  const [keyInputs, setKeyInputs] = useState<Record<string, string>>({});
  const [savingKey, setSavingKey] = useState<string | null>(null);
  const socket = useSocket();

  const [translationReady, setTranslationReady] = useState(false);

  const fetchMarketplace = useCallback(async () => {
    try {
      const res = await fetch(`/api/marketplace/skills?lang=${lang}`, { credentials: 'include' });
      if (res.ok) setMarketSkills(await res.json());
    } catch {}
  }, [lang]);

  const fetchInstalled = useCallback(async () => {
    try {
      const res = await fetch('/api/skills', { credentials: 'include' });
      if (res.ok) {
        const data = await res.json();
        setInstalledSkills(data.skills || []);
      }
    } catch {}
    setLoading(false);
  }, []);

  const fetchCategories = useCallback(async () => {
    try {
      const res = await fetch(`/api/marketplace/categories?lang=${lang}`, { credentials: 'include' });
      if (res.ok) setCategories((await res.json()).map((c: any) => c.name));
    } catch {}
  }, [lang]);

  // External search (npm + GitHub) — debounced
  const fetchExternal = useCallback(async (q: string) => {
    if (!q || q.length < 2) { setNpmResults([]); setGithubResults([]); return; }
    setSearchingExternal(true);
    setExternalError('');
    const qClean = encodeURIComponent(q);
    try {
      const [npmRes, ghRes] = await Promise.allSettled([
        fetch(`/api/marketplace/discover/npm?q=${qClean}`).then(async r => {
          if (!r.ok) throw new Error((await r.json().catch(() => ({}))).error || `npm search failed (${r.status})`);
          return r.json();
        }),
        fetch(`/api/marketplace/discover/github?topic=${qClean}`).then(async r => {
          if (!r.ok) throw new Error((await r.json().catch(() => ({}))).error || `GitHub search failed (${r.status})`);
          return r.json();
        }),
      ]);
      setNpmResults((npmRes.status === 'fulfilled' ? npmRes.value?.results || [] : []).slice(0, 6));
      setGithubResults((ghRes.status === 'fulfilled' ? ghRes.value?.results || [] : []).slice(0, 6));
      const errors = [npmRes, ghRes]
        .filter((r): r is PromiseRejectedResult => r.status === 'rejected')
        .map(r => r.reason?.message)
        .filter(Boolean);
      if (errors.length) setExternalError(errors.join(' / '));
    } catch (err: any) {
      setExternalError(err.message || 'External search failed');
    }
    setSearchingExternal(false);
  }, []);

  const fetchSavedKeys = useCallback(async () => {
    try {
      const res = await fetch('/api/settings/keys', { credentials: 'include' });
      if (res.ok) setSavedKeys(await res.json());
    } catch {}
  }, []);

  useEffect(() => { fetchMarketplace(); fetchInstalled(); fetchCategories(); fetchSavedKeys(); }, [fetchMarketplace, fetchInstalled, fetchCategories, fetchSavedKeys]);

  // Debounced external search
  useEffect(() => {
    const timer = setTimeout(() => fetchExternal(search), 400);
    return () => clearTimeout(timer);
  }, [search, fetchExternal]);

  // Translate on first Chinese load, then re-fetch to show translated data
  useEffect(() => {
    let cancelled = false;
    if (lang === 'zh' && !translationReady) {
      fetch('/api/marketplace/translate?lang=zh', { method: 'POST' })
        .then(() => { if (!cancelled) { setTranslationReady(true); fetchMarketplace(); } })
        .catch(() => {});
    }
    return () => { cancelled = true; };
  }, [lang, translationReady, fetchMarketplace]);

  // Socket events for real-time updates
  useEffect(() => {
    if (!socket) return;
    const refresh = () => { fetchInstalled(); fetchMarketplace(); };
    const onInstalling = (data: { skillId: string; name: string; stage: string }) => {
      setInstallProgress({ skillId: data.skillId, stage: data.stage });
    };
    const onInstalled = () => {
      setInstallProgress(null);
      refresh();
    };
    socket.on('skill:installing', onInstalling);
    socket.on('skill:installed', onInstalled);
    socket.on('skill:uninstalled', refresh);
    socket.on('skill:updated', refresh);
    return () => {
      socket.off('skill:installing', onInstalling);
      socket.off('skill:installed', onInstalled);
      socket.off('skill:uninstalled', refresh);
      socket.off('skill:updated', refresh);
    };
  }, [socket, fetchInstalled, fetchMarketplace]);

  const handleInstall = async (skill: MarketplaceSkill | ExternalResult) => {
    if ('installed' in skill && skill.installed) return;
    setInstalling(skill.id);
    try {
      const body: any = { skillId: skill.id, skillName: skill.name, installSource: skill.installSource };
      if ('installPath' in skill && skill.installPath) body.installPath = skill.installPath;
      if ('npmPackage' in skill && skill.npmPackage) body.npmPackage = skill.npmPackage;
      if ('repoUrl' in skill && skill.repoUrl) body.repoUrl = skill.repoUrl;
      const res = await fetch('/api/marketplace/skills/acquire', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(body),
        credentials: 'include',
      });
      const data = await res.json();
      if (data.success) {
        toast.success(`"${skill.name}" ${t.skillInstalledToast}`);
        if (socket) socket.emit('skill:installed', { skillId: skill.id, name: skill.name });
        fetchInstalled(); fetchMarketplace();
        // Clear external results after successful install
        setNpmResults(prev => prev.filter(s => s.id !== skill.id));
        setGithubResults(prev => prev.filter(s => s.id !== skill.id));
      } else toast.error(data.error || 'Install failed');
    } catch (err: any) { toast.error(err.message); }
    finally { setInstalling(null); }
  };

  const handleUninstall = async (name: string) => {
    try {
      const res = await fetch(`/api/skills/${name}`, { method: 'DELETE', credentials: 'include' });
      if (res.ok) {
        toast.success(`"${name}" ${t.skillUninstalledToast}`);
        if (socket) socket.emit('skill:uninstalled', { name });
        fetchInstalled(); fetchMarketplace();
      } else {
        const data = await res.json().catch(() => ({}));
        toast.error(data.error || 'Uninstall failed');
      }
    } catch (err: any) { toast.error(err.message); }
  };

  const handleToggle = async (name: string, enabled: boolean) => {
    try {
      const res = await fetch(`/api/skills/${name}/${enabled ? 'enable' : 'disable'}`, { method: 'POST', credentials: 'include' });
      if (!res.ok) {
        const data = await res.json().catch(() => ({}));
        throw new Error(data.error || 'Toggle failed');
      }
      toast.success(`${enabled ? t.skillEnabledToast : t.skillDisabledToast} ${name}`);
      fetchInstalled();
    } catch (err: any) {
      toast.error(err.message || 'Toggle failed');
    }
  };

  const handleSaveKey = async (envKey: string, value: string) => {
    if (!value.trim()) return;
    setSavingKey(envKey);
    try {
      await fetch('/api/settings/keys', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ keys: { [envKey]: value.trim() } }),
        credentials: 'include',
      });
      setSavedKeys(prev => ({ ...prev, [envKey]: true }));
      setKeyInputs(prev => { const n = { ...prev }; delete n[envKey]; return n; });
      toast.success(`${envKey} saved`);
    } catch { toast.error('Failed to save key'); }
    finally { setSavingKey(null); }
  };

  const handleGenerate = async () => {
    if (!genDescription.trim()) return;
    setGenerating(true);
    try {
      const res = await fetch('/api/skills/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ description: genDescription }),
        credentials: 'include',
      });
      const data = await res.json();
      if (data.success) {
        toast.success(t.skillGeneratedToast);
        setGenDescription(''); fetchInstalled();
        if (socket) socket.emit('skill:updated', { name: data.skillName });
      } else toast.error(data.error || 'Generation failed');
    } catch (err: any) { toast.error(err.message); }
    finally { setGenerating(false); }
  };

  const handlePublish = async (skillName: string) => {
    try {
      const installed = installedSkills.find(s => s.name === skillName);
      if (!installed) return;
      const res = await fetch('/api/marketplace/publish', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          name: skillName,
          description: installed.description,
          author: 'Community',
          category: 'Generated',
          toolCount: installed.toolCount,
        }),
      });
      if (res.ok) toast.success(`Published "${skillName}" to community!`);
    } catch {}
  };

  // Filter & sort
  const filteredMarket = marketSkills.filter(s => {
    if (search && !s.name.toLowerCase().includes(search.toLowerCase()) && !s.description.toLowerCase().includes(search.toLowerCase())) return false;
    if (activeCategory && s.category !== activeCategory) return false;
    return true;
  });

  const sortedMarket = [...filteredMarket].sort((a, b) => {
    if (sortKey === 'downloads') return b.downloads - a.downloads;
    if (sortKey === 'rating') return b.rating - a.rating;
    return 0;
  });

  const tabs: { id: Tab; label: string; icon: React.ReactNode }[] = [
    { id: 'featured', label: t.featuredTab || 'Featured', icon: <Sparkles size={14} /> },
    { id: 'marketplace', label: t.marketplaceTab || 'Marketplace', icon: <ShoppingBag size={14} /> },
    { id: 'installed', label: t.installedTab || 'Installed', icon: <Cpu size={14} /> },
    { id: 'generate', label: t.generateTab || 'Generate', icon: <Sparkles size={14} /> },
  ];

  const SAMPLE_PROMPTS = [
    t.skillGeneratePlaceholder || 'e.g. Check if a website is down, generate QR codes...',
    '', '', '', '',
  ];

  return (
    <div className="space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-500">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-3">
          <Zap className="text-celestial-saturn" size={20} />
          <h3 className="text-xl font-bold uppercase tracking-tighter text-white/90">{t.skillCenter || 'Skill Center'}</h3>
        </div>
        <div className="flex items-center gap-2">
          <span className="text-xs text-white/45 font-mono">{sortedMarket.length} {t.available || 'available'}</span>
          <button
            onClick={() => { fetchMarketplace(); fetchInstalled(); }}
            className="p-2 rounded-lg hover:bg-white/5 text-white/55 hover:text-white/60 transition-all"
          >
            <RefreshCw size={14} />
          </button>
        </div>
      </div>

      <p className="text-sm text-white/40 max-w-xl">
        {t.skillMarketDesc || `Browse, install and generate MCP skills. Each skill expands Gaea's capabilities with new tools, APIs, and automations. Installed skills appear in your MCP ecosystem.`}
      </p>

      {/* Tabs */}
      <div className="flex gap-1 bg-white/5 rounded-xl p-1 w-fit">
        {tabs.map(tab => (
          <button
            key={tab.id}
            onClick={() => setActiveTab(tab.id)}
            className={`flex items-center gap-1.5 px-4 py-2 rounded-lg text-xs font-bold transition-all ${
              activeTab === tab.id
                ? 'bg-white/10 text-white'
                : 'text-white/55 hover:text-white/50'
            }`}
          >
            {tab.icon}
            {tab.label}
            {tab.id === 'installed' && installedSkills.length > 0 && (
              <span className="text-xs px-1.5 py-0.5 bg-white/10 rounded-full text-white/40">{installedSkills.length}</span>
            )}
          </button>
        ))}
      </div>

      {/* Content */}
      <AnimatePresence mode="wait">
        {detailSkill ? <SkillDetailPane detailSkill={detailSkill} setDetailSkill={setDetailSkill} t={t} marketSkills={marketSkills} installing={installing} savedKeys={savedKeys} keyInputs={keyInputs} setKeyInputs={setKeyInputs} savingKey={savingKey} handleInstall={handleInstall} handleSaveKey={handleSaveKey} handleToggle={handleToggle} handleUninstall={handleUninstall} /> :

        activeTab === 'featured' && (
          <motion.div key="featured" initial={{ opacity: 0, y: 6 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -6 }} transition={{ duration: 0.15 }} className="space-y-6">
            <div className="grid grid-cols-1 gap-4">
              {/* Hero cards: first 2 skills */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {FEATURED_SKILLS.slice(0, 2).map((skill, idx) => {
                  const isInstalled = marketSkills.find(s => s.id === `skill-${skill.id}`)?.installed;
                  const isInstalling = installing === `skill-${skill.id}`;
                  return (
                    <motion.div
                      key={skill.id}
                      initial={{ opacity: 0, y: 10 }}
                      animate={{ opacity: 1, y: 0 }}
                      onClick={() => {
                        const skillData = marketSkills.find(s => s.id === `skill-${skill.id}`);
                        setDetailSkill(skillData || {
                          id: `skill-${skill.id}`,
                          name: skill.name,
                          description: skill.desc,
                          author: 'Gaea Official',
                          downloads: 0,
                          rating: 0,
                          category: '',
                          icon: skill.icon,
                          installSource: 'bundled' as const,
                          installed: false,
                        });
                      }}
                      className={`relative p-8 rounded-[2.5rem] border border-white/10 overflow-hidden group cursor-pointer ${
                        idx === 0 ? 'bg-gradient-to-br from-purple-500/10 via-transparent to-pink-500/5' : 'bg-gradient-to-br from-amber-500/10 via-transparent to-yellow-500/5'
                      }`}
                    >
                      <div className="absolute inset-0 bg-[radial-gradient(circle_at_50%_0%,rgba(255,255,255,0.03),transparent_70%)]" />
                      <div className="relative z-10 space-y-5">
                        <div className="flex items-center gap-4">
                          <div className={`w-14 h-14 rounded-2xl bg-gradient-to-br ${skill.iconColor} flex items-center justify-center shadow-2xl`}>
                            {ICON_COMPONENTS[skill.icon] || <Zap size={24} className="text-white" />}
                          </div>
                          <div>
                            <h3 className="text-lg font-black text-white tracking-tight">{skill.name}</h3>
                            <span className="text-xs text-white/55 font-mono uppercase tracking-widest">{t.flagshipSkill || 'Flagship Skill'}</span>
                          </div>
                        </div>
                        <p className="text-sm text-white/50 leading-relaxed">{skill.desc}</p>
                        <div className="flex items-center gap-3">
                          <Button
                            onClick={(e) => {
                              e.stopPropagation();
                              const skillData = marketSkills.find(s => s.id === `skill-${skill.id}`);
                              if (skillData && !skillData.installed) handleInstall(skillData);
                            }}
                            disabled={isInstalled || isInstalling}
                            className={`text-xs font-bold px-5 py-2.5 h-auto rounded-xl transition-all ${
                              isInstalled ? 'bg-green-500/20 text-green-400' : 'bg-white text-black hover:scale-105'
                            }`}
                          >
                            {isInstalled ? <><CheckCircle size={14} className="mr-1" /> {t.installedStatus || 'Installed'}</> : isInstalling ? <><RefreshCw size={14} className="mr-1 animate-spin" /> {t.installingStatus || 'Installing...'}</> : <><Download size={14} className="mr-1" /> {t.installBtn || 'Install'}</>}
                          </Button>
                          <span className="text-xs text-white/45 font-mono">{t.tryPrompt || 'Try: '}"{skill.prompt.slice(0, 40)}..."</span>
                        </div>
                      </div>
                    </motion.div>
                  );
                })}
              </div>

              {/* Remaining 4 skills in a 2x2 grid */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                {FEATURED_SKILLS.slice(2).map(skill => {
                  const isInstalled = marketSkills.find(s => s.id === `skill-${skill.id}`)?.installed;
                  const isInstalling = installing === `skill-${skill.id}`;
                  return (
                    <motion.div
                      key={skill.id}
                      initial={{ opacity: 0, y: 6 }}
                      animate={{ opacity: 1, y: 0 }}
                      onClick={() => {
                        const skillData = marketSkills.find(s => s.id === `skill-${skill.id}`);
                        setDetailSkill(skillData || {
                          id: `skill-${skill.id}`,
                          name: skill.name,
                          description: skill.desc,
                          author: 'Gaea Official',
                          downloads: 0,
                          rating: 0,
                          category: '',
                          icon: skill.icon,
                          installSource: 'bundled' as const,
                          installed: false,
                        });
                      }}
                      className="p-5 bg-white/5 rounded-2xl border border-white/5 hover:border-white/10 transition-all group flex items-center gap-4 cursor-pointer"
                    >
                      <div className={`w-10 h-10 rounded-xl bg-gradient-to-br ${skill.iconColor} flex items-center justify-center shrink-0`}>
                        {ICON_COMPONENTS[skill.icon] || <Zap size={18} className="text-white" />}
                      </div>
                      <div className="flex-1 min-w-0">
                        <h4 className="font-bold text-white/80 text-sm">{skill.name}</h4>
                        <p className="text-xs text-white/55 leading-relaxed line-clamp-1">{skill.prompt}</p>
                      </div>
                      <Button
                        onClick={(e) => {
                          e.stopPropagation();
                          const skillData = marketSkills.find(s => s.id === `skill-${skill.id}`);
                          if (skillData && !skillData.installed) handleInstall(skillData);
                        }}
                        disabled={isInstalled || isInstalling}
                        className={`text-xs font-bold px-3 py-1.5 h-auto rounded-lg shrink-0 transition-all ${
                          isInstalled ? 'bg-green-500/20 text-green-400' : 'bg-white/10 text-white/60 hover:bg-white/20'
                        }`}
                      >
                        {isInstalled ? <><CheckCircle size={12} /> {t.installedStatus || 'Installed'}</> : isInstalling ? <><RefreshCw size={12} className="animate-spin" /> {t.installingStatus || 'Installing...'}</> : <><Download size={12} /> {t.installBtn || 'Install'}</>}
                      </Button>
                    </motion.div>
                  );
                })}
              </div>
            </div>
          </motion.div>
        )}

        {activeTab === 'marketplace' && (
          <motion.div key="marketplace" initial={{ opacity: 0, y: 6 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -6 }} transition={{ duration: 0.15 }} className="space-y-6">
            {/* Install progress banner */}
            <AnimatePresence>
              {installProgress && (
                <motion.div initial={{ opacity: 0, height: 0 }} animate={{ opacity: 1, height: 'auto' }} exit={{ opacity: 0, height: 0 }} className="overflow-hidden">
                  <div className="flex items-center gap-3 px-4 py-3 bg-celestial-saturn/10 border border-celestial-saturn/20 rounded-2xl">
                    <RefreshCw size={14} className="animate-spin text-celestial-saturn" />
                    <div>
                      <span className="text-xs font-bold text-celestial-saturn uppercase">
                        {installProgress.stage === 'downloading' ? (t.installingStatus || 'Downloading...') :
                         installProgress.stage === 'copying' ? (t.installingStatus || 'Copying files...') :
                         installProgress.stage === 'connecting' ? (t.connectingStage || 'Connecting...') :
                         (t.installingStatus || 'Installing...')}
                      </span>
                    </div>
                  </div>
                </motion.div>
              )}
            </AnimatePresence>
            {/* Filters row */}
            <div className="flex items-center gap-3 flex-wrap">
              <div className="relative flex-1 min-w-[200px]">
                <Search size={13} className="absolute left-3 top-1/2 -translate-y-1/2 text-white/45" />
                <Input value={search} onChange={e => setSearch(e.target.value)} placeholder={t.searchSkills || 'Search skills...'} className="w-full pl-9 bg-white/5 border-white/10 rounded-xl py-2 text-xs" />
              </div>
              {/* Category filter */}
              <div className="flex items-center gap-1.5 flex-wrap">
                <button
                  onClick={() => setActiveCategory('')}
                  className={`px-3 py-1.5 rounded-lg text-xs font-bold transition-all ${!activeCategory ? 'bg-white/10 text-white' : 'bg-white/5 text-white/55 hover:text-white/50'}`}
                >
                  {t.allCategories || 'All'}
                </button>
                {categories.map(cat => (
                  <button
                    key={cat}
                    onClick={() => setActiveCategory(activeCategory === cat ? '' : cat)}
                    className={`px-3 py-1.5 rounded-lg text-xs font-bold transition-all ${activeCategory === cat ? 'bg-celestial-saturn/20 text-celestial-saturn' : 'bg-white/5 text-white/55 hover:text-white/50'}`}
                  >
                    {cat}
                  </button>
                ))}
              </div>
              {/* Sort */}
              <div className="flex items-center gap-1.5">
                <span className="text-[12px] text-white/45">{t.sortBy || 'Sort'}:</span>
                {(['downloads', 'rating', 'newest'] as SortKey[]).map(k => (
                  <button
                    key={k}
                    onClick={() => setSortKey(k)}
                    className={`px-2 py-1 rounded-md text-[12px] font-bold transition-all ${sortKey === k ? 'bg-white/10 text-white' : 'text-white/45 hover:text-white/40'}`}
                  >
                    {(t as any)[k] || k}
                  </button>
                ))}
              </div>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <AnimatePresence>
                {sortedMarket.map(skill => (
                  <motion.div
                    key={skill.id}
                    initial={{ opacity: 0, y: 10 }}
                    animate={{ opacity: 1, y: 0 }}
                    exit={{ opacity: 0 }}
                    onClick={() => setDetailSkill(skill)}
                    className="p-6 bg-white/5 rounded-3xl border border-white/5 hover:border-white/10 transition-all group cursor-pointer"
                  >
                    {/* Header */}
                    <div className="flex items-start justify-between mb-4">
                      <div className="flex items-center gap-3 min-w-0">
                        <div className={`w-10 h-10 rounded-xl border flex items-center justify-center shrink-0 ${ICON_CLASSES[skill.icon] || 'bg-white/5 text-white/55 border-white/10'}`}>
                          {ICON_COMPONENTS[skill.icon] || <Zap size={18} />}
                        </div>
                        <div className="min-w-0">
                          <h4 className="font-bold text-white/90 text-sm">{skill.name}</h4>
                          <span className="text-xs text-white/55 font-mono">{t.version || 'v'} {skill.version || '1.0'} &middot; {skill.toolCount || 1} {t.toolsCount || 'tools'}</span>
                        </div>
                      </div>
                      <div className="flex items-center gap-1.5 shrink-0">
                        {skill.requiresApiKey && (
                          <span className="flex items-center gap-1 px-2 py-0.5 bg-amber-500/10 rounded-full text-xs font-bold uppercase text-amber-400" title={(t.requiresApiKey || 'Requires') + ' ' + skill.apiKeyEnv + ' API key'}>
                            <Key size={8} /> API
                          </span>
                        )}
                        {skill.requiresSetup && (
                          <span className="flex items-center gap-1 px-2 py-0.5 bg-purple-500/10 rounded-full text-xs font-bold uppercase text-purple-400" title={skill.setupNote || (t.setupRequired || 'Requires manual setup')}>
                            <Wrench size={8} /> Setup
                          </span>
                        )}
                        {skill.installed && (
                          <span className="flex items-center gap-1 px-2 py-1 bg-green-500/10 rounded-full text-[12px] font-bold uppercase text-green-400">
                            <CheckCircle size={10} /> {t.installedStatus || 'Installed'}
                          </span>
                        )}
                      </div>
                    </div>

                    <p className="text-xs text-white/50 leading-relaxed mb-4 line-clamp-2">{skill.description}</p>

                    {/* Setup note */}
                    {skill.requiresSetup && skill.setupNote && (
                      <div className="mb-3 p-2 bg-purple-500/5 border border-purple-500/10 rounded-xl">
                        <p className="text-[12px] text-purple-300/70 leading-relaxed">{skill.setupNote}</p>
                      </div>
                    )}
                    {skill.requiresApiKey && skill.apiKeyUrl && (
                      <div className="mb-3 p-2 bg-amber-500/5 border border-amber-500/10 rounded-xl">
                        <p className="text-[12px] text-amber-300/70 leading-relaxed">
                          Requires <strong>{skill.apiKeyEnv}</strong> — <a href={skill.apiKeyUrl} target="_blank" rel="noopener" className="underline hover:text-amber-200">{t.getApiKey || 'get API key'}</a>
                        </p>
                      </div>
                    )}

                    {/* Tags */}
                    <div className="flex items-center gap-2 flex-wrap mb-4">
                      <span className="flex items-center gap-1 px-2 py-0.5 bg-white/5 rounded-full text-[12px] text-white/55">
                        <Tag size={8} /> {skill.category}
                      </span>
                      <span className="text-[12px] text-white/45">{skill.author}</span>
                    </div>

                    {/* Footer */}
                    <div className="flex items-center justify-between">
                      <div className="flex items-center gap-4">
                        <span className="flex items-center gap-1 text-xs text-white/45">
                          <Download size={10} /> {skill.downloads.toLocaleString()}
                        </span>
                        <span className="flex items-center gap-1 text-xs text-white/45">
                          <Star size={10} className="text-amber-400" fill="currentColor" /> {skill.rating > 0 ? skill.rating.toFixed(1) : '--'}
                        </span>
                      </div>
                      <Button
                        onClick={(e) => { e.stopPropagation(); handleInstall(skill); }}
                        disabled={skill.installed || installing === skill.id}
                        className={`text-xs font-bold px-3 py-1.5 h-auto rounded-xl transition-all ${
                          skill.installed
                            ? 'bg-green-500/20 text-green-400 cursor-default'
                            : installing === skill.id
                              ? 'bg-celestial-saturn/50 text-black cursor-wait'
                              : 'bg-celestial-saturn text-black hover:scale-105'
                        }`}
                      >
                        {skill.installed ? (
                          <><CheckCircle size={12} className="mr-1" /> {t.installedStatus || 'Installed'}</>
                        ) : installing === skill.id ? (
                          <><RefreshCw size={12} className="mr-1 animate-spin" /> {t.installingStatus || 'Installing...'}</>
                        ) : (
                          <><Download size={12} className="mr-1" /> {t.installBtn || 'Install'}</>
                        )}
                      </Button>
                    </div>
                  </motion.div>
                ))}
              </AnimatePresence>
            </div>
            {sortedMarket.length === 0 && (
              <div className="p-16 bg-white/5 rounded-[2rem] border border-white/5 text-center">
                <ShoppingBag size={40} className="text-white/45 mx-auto mb-4" />
                <p className="text-white/40 font-bold uppercase tracking-widest text-sm">{t.noSkillsFound || 'No skills found'}</p>
                <p className="text-white/45 text-xs mt-2">{search || activeCategory ? (t.skillNoResultsFilter || 'No results. Try different filters.') : (t.skillCheckBack || 'Check back soon or generate your own.')}</p>
              </div>
            )}

            {/* External search results: npm + GitHub */}
            <AnimatePresence>
              {searchingExternal && (
                <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="flex items-center gap-2 text-xs text-white/45 py-2">
                  <RefreshCw size={12} className="animate-spin" /> Searching npm & GitHub...
                </motion.div>
              )}

              {externalError && (
                <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="text-xs text-red-300/80 bg-red-500/10 border border-red-500/15 rounded-xl px-3 py-2">
                  {externalError}
                </motion.div>
              )}

              {/* npm registry results */}
              {npmResults.length > 0 && (
                <motion.div key="npm-section" initial={{ opacity: 0, y: 6 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0 }} className="space-y-2">
                  <div className="flex items-center gap-2 px-1">
                    <span className="text-xs font-bold uppercase text-red-400 tracking-wider">npm Registry</span>
                    <span className="text-[12px] text-white/45 font-mono">{npmResults.length} found</span>
                  </div>
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                    {npmResults.map(skill => {
                      const isInstalling = installing === skill.id;
                      return (
                        <div key={skill.id}
                          className="p-4 bg-red-500/5 rounded-2xl border border-red-500/10 hover:border-red-500/20 transition-all flex items-center gap-3">
                          <div className="w-8 h-8 rounded-lg bg-red-500/10 flex items-center justify-center shrink-0">
                            <Download size={14} className="text-red-400" />
                          </div>
                          <div className="flex-1 min-w-0">
                            <h5 className="text-xs font-bold text-white/80 truncate">{skill.name}</h5>
                            <p className="text-xs text-white/55 line-clamp-1">{skill.description || skill.version || ''}</p>
                          </div>
                          <Button
                            onClick={() => handleInstall(skill)}
                            disabled={isInstalling}
                            className="text-xs font-bold px-3 py-1.5 h-auto rounded-lg shrink-0 bg-red-500/20 text-red-400 hover:bg-red-500/30 transition-all"
                          >
                            {isInstalling ? <RefreshCw size={11} className="animate-spin" /> : t.installBtn || 'Install'}
                          </Button>
                        </div>
                      );
                    })}
                  </div>
                </motion.div>
              )}

              {/* GitHub results */}
              {githubResults.length > 0 && (
                <motion.div key="github-section" initial={{ opacity: 0, y: 6 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0 }} className="space-y-2">
                  <div className="flex items-center gap-2 px-1">
                    <Globe size={11} className="text-purple-400" />
                    <span className="text-xs font-bold uppercase text-purple-400 tracking-wider">GitHub</span>
                    <span className="text-[12px] text-white/45 font-mono">{githubResults.length} repos</span>
                  </div>
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                    {githubResults.map(repo => {
                      const isInstalling = installing === repo.id;
                      return (
                        <div key={repo.id}
                          className="p-4 bg-purple-500/5 rounded-2xl border border-purple-500/10 hover:border-purple-500/20 transition-all flex items-center gap-3">
                          <div className="w-8 h-8 rounded-lg bg-purple-500/10 flex items-center justify-center shrink-0">
                            <Star size={14} className="text-purple-400" />
                          </div>
                          <div className="flex-1 min-w-0">
                            <h5 className="text-xs font-bold text-white/80 truncate">{repo.name}</h5>
                            <p className="text-xs text-white/55 line-clamp-1">
                              {repo.stars ? `★ ${repo.stars} · ` : ''}{repo.description || repo.language || ''}
                            </p>
                          </div>
                          <Button
                            onClick={() => handleInstall(repo)}
                            disabled={isInstalling}
                            className="text-xs font-bold px-3 py-1.5 h-auto rounded-lg shrink-0 bg-purple-500/20 text-purple-400 hover:bg-purple-500/30 transition-all"
                          >
                            {isInstalling ? <RefreshCw size={11} className="animate-spin" /> : t.installBtn || 'Install'}
                          </Button>
                        </div>
                      );
                    })}
                  </div>
                </motion.div>
              )}
            </AnimatePresence>
          </motion.div>
        )}

        {activeTab === 'installed' && (
          <motion.div key="installed" initial={{ opacity: 0, y: 6 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -6 }} transition={{ duration: 0.15 }} className="space-y-6">
            {loading ? (
              <div className="p-16 bg-white/5 rounded-[2rem] border border-white/5 text-center">
                <p className="text-white/40 text-sm">{t.loading || 'Loading...'}</p>
              </div>
            ) : installedSkills.length === 0 ? (
              <div className="p-16 bg-white/5 rounded-[2rem] border border-white/5 text-center">
                <Wrench size={40} className="text-white/45 mx-auto mb-4" />
                <p className="text-white/40 font-bold uppercase tracking-widest text-sm">{t.noSkillsInstalled || 'No skills installed'}</p>
                <p className="text-white/45 text-xs mt-2">{t.skillBrowseMarketplace || 'Browse the marketplace or generate one.'}</p>
              </div>
            ) : (
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <AnimatePresence>
                  {installedSkills.map(skill => (
                    <motion.div
                      key={skill.name}
                      initial={{ opacity: 0, y: 10 }}
                      animate={{ opacity: 1, y: 0 }}
                      exit={{ opacity: 0 }}
                      onClick={() => setDetailSkill(skill)}
                      className="p-6 bg-white/5 rounded-3xl border border-white/5 hover:border-white/10 transition-all cursor-pointer"
                    >
                      <div className="flex items-start justify-between mb-4">
                        <div className="flex-1 min-w-0">
                          <h4 className="font-bold text-white/90 text-sm">{skill.name}</h4>
                          <span className="text-xs text-white/55 font-mono">{skill.toolCount} {t.toolsCount || 'tools'}{skill.installedAt ? ` · ${new Date(skill.installedAt).toLocaleDateString()}` : ''}</span>
                        </div>
                        <div className="flex items-center gap-1 shrink-0">
                          <button onClick={(e) => { e.stopPropagation(); handleToggle(skill.name, !skill.enabled); }}
                            className={`p-2 rounded-lg transition-colors ${skill.enabled ? 'text-green-400 hover:bg-green-500/10' : 'text-white/45 hover:bg-white/5'}`}
                            title={skill.enabled ? (t.skillDisableBtn || 'Disable') : (t.skillEnableBtn || 'Enable')}
                          >
                            {skill.enabled ? <Power size={13} /> : <PowerOff size={13} />}
                          </button>
                          <button onClick={(e) => { e.stopPropagation(); handlePublish(skill.name); }}
                            className="p-2 hover:bg-violet-500/10 rounded-lg text-white/45 hover:text-violet-400 transition-colors"
                            title={t.publishBtn || 'Publish'}
                          >
                            <Upload size={13} />
                          </button>
                          <button onClick={(e) => { e.stopPropagation(); handleUninstall(skill.name); }}
                            className="p-2 hover:bg-red-500/10 rounded-lg text-white/45 hover:text-red-400 transition-colors"
                            title={t.uninstallBtn || 'Uninstall'}
                          >
                            <Trash2 size={13} />
                          </button>
                        </div>
                      </div>

                      <p className="text-xs text-white/50 leading-relaxed mb-4 line-clamp-2">{skill.description}</p>

                      {/* Tags */}
                      <div className="flex items-center gap-2 flex-wrap">
                        {skill.autoGenerated && (
                          <span className="flex items-center gap-1 px-2 py-0.5 bg-emerald-500/10 rounded-full text-[12px] text-emerald-400 font-bold">{t.autoGenerated || 'Auto'}</span>
                        )}
                        {skill.connected && (
                          <span className="flex items-center gap-1 px-2 py-0.5 bg-green-500/10 rounded-full text-[12px] text-green-400 font-bold">{t.connected || 'Connected'}</span>
                        )}
                        <span className={`flex items-center gap-1 px-2 py-0.5 rounded-full text-[12px] font-bold ${skill.enabled ? 'bg-green-500/10 text-green-400' : 'bg-white/5 text-white/45'}`}>
                          {skill.enabled ? (t.enabled || 'Enabled') : (t.disabled || 'Disabled')}
                        </span>
                      </div>
                    </motion.div>
                  ))}
                </AnimatePresence>
              </div>
            )}
          </motion.div>
        )}

        {activeTab === 'generate' && (
          <motion.div key="generate" initial={{ opacity: 0, y: 6 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -6 }} transition={{ duration: 0.15 }} className="space-y-6">
            <div className="p-6 bg-white/5 rounded-3xl border border-white/5 space-y-4">
              <div className="flex items-center gap-3">
                <Sparkles className="text-celestial-saturn" size={18} />
                <h4 className="text-sm font-bold uppercase tracking-tight text-white">{t.generateNewSkill || 'Generate a New Skill'}</h4>
              </div>
              <p className="text-xs text-white/55 leading-relaxed">
                {t.skillGenerateDesc || 'Describe what the skill should do. Gaea generates a complete MCP server package.'}
              </p>
              <div className="flex gap-2">
                <Input value={genDescription} onChange={e => setGenDescription(e.target.value)}
                  placeholder={t.skillGeneratePlaceholder || 'e.g. Check if a website is down...'}
                  className="flex-1 bg-white/5 border-white/10 rounded-xl py-2 text-xs"
                  onKeyDown={e => e.key === 'Enter' && handleGenerate()} />
                <Button onClick={handleGenerate} disabled={generating || !genDescription.trim()}
                  className="bg-celestial-saturn text-black font-bold text-xs px-5 py-2 rounded-xl hover:scale-105 transition-transform disabled:opacity-40">
                  {generating ? (t.generating || '...') : (t.generateBtn || 'Generate')}
                </Button>
              </div>
              <div className="flex gap-2 flex-wrap">
                {SAMPLE_PROMPTS.map(ex => (
                  <button key={ex} onClick={() => setGenDescription(ex)} className="text-[12px] px-2 py-1 rounded-lg bg-white/5 border border-white/5 text-white/55 hover:text-white/50 hover:border-white/10 transition-colors">
                    {ex}
                  </button>
                ))}
              </div>
            </div>
          </motion.div>
        )}


      </AnimatePresence>
    </div>
  );
}

function SkillDetailPane({ detailSkill, setDetailSkill, t, marketSkills, installing, savedKeys, keyInputs, setKeyInputs, savingKey, handleInstall, handleSaveKey, handleToggle, handleUninstall }: {
  detailSkill: any;
  setDetailSkill: (v: any) => void;
  t: any;
  marketSkills: any[];
  installing: string | null;
  savedKeys: Record<string, boolean>;
  keyInputs: Record<string, string>;
  setKeyInputs: React.Dispatch<React.SetStateAction<Record<string, string>>>;
  savingKey: string | null;
  handleInstall: (skill: any) => void;
  handleSaveKey: (envKey: string, value: string) => void;
  handleToggle: (name: string, enabled: boolean) => void;
  handleUninstall: (name: string) => void;
}) {
  const isMarketSkill = 'id' in detailSkill;
  const mSkill: any | undefined = isMarketSkill
    ? detailSkill
    : marketSkills.find(s => s.id === `skill-${detailSkill.name}`);
  return (
    <motion.div
      key={(detailSkill as any).id || (detailSkill as any).name || 'detail'}
      initial={{ opacity: 0, x: 20 }}
      animate={{ opacity: 1, x: 0 }}
      exit={{ opacity: 0, x: -20 }}
      className="p-6 bg-white/5 rounded-3xl border border-white/10 space-y-5"
    >
      <button
        onClick={() => setDetailSkill(null)}
        className="flex items-center gap-2 text-xs font-bold text-white/45 hover:text-white/70 transition-colors"
      >
        <ChevronDown size={14} className="rotate-90" /> {t.back || 'Back'}
      </button>

      <div className="flex items-center gap-3">
        <div className={`w-12 h-12 rounded-xl border flex items-center justify-center shrink-0 ${
          mSkill ? ICON_CLASSES[mSkill.icon] || 'bg-white/5 text-white/55 border-white/10' : 'bg-white/5 text-white/55 border-white/10'
        }`}>
          {mSkill ? (ICON_COMPONENTS[mSkill.icon] || <Zap size={22} />) : <Zap size={22} />}
        </div>
        <div>
          <h3 className="text-lg font-bold text-white">
            {mSkill?.name ?? detailSkill.name}
          </h3>
          {mSkill && (
            <span className="text-xs text-white/55 font-mono">
              v {mSkill.version || '1.0'} &middot; {mSkill.toolCount || 1} tools
            </span>
          )}
        </div>
      </div>

      <div className="flex flex-wrap items-center gap-3 text-xs text-white/45">
        {mSkill && (
          <>
            <span className="flex items-center gap-1"><Tag size={10} /> {mSkill.category}</span>
            <span>{mSkill.author}</span>
            <span className="flex items-center gap-1"><Download size={10} /> {mSkill.downloads.toLocaleString()}</span>
            <span className="flex items-center gap-1"><Star size={10} className="text-amber-400" fill="currentColor" /> {mSkill.rating > 0 ? mSkill.rating.toFixed(1) : '--'}</span>
          </>
        )}
        {!isMarketSkill && detailSkill && (
          <>
            <span>{detailSkill.toolCount} tools</span>
            {detailSkill.installedAt && (
              <span>Installed {new Date(detailSkill.installedAt).toLocaleDateString()}</span>
            )}
            <span>{detailSkill.source}</span>
          </>
        )}
      </div>

      <p className="text-sm text-white/60 leading-relaxed">
        {mSkill?.description ?? detailSkill.description}
      </p>

      {mSkill?.runtime === 'external' && (
        <div className="p-4 bg-cyan-500/5 border border-cyan-500/10 rounded-2xl space-y-2">
          <span className="flex items-center gap-1.5 text-xs font-bold uppercase text-cyan-400">
            <ExternalLink size={12} /> External Runtime
          </span>
          {mSkill.externalCommand && (
            <p className="text-sm font-mono text-cyan-300/70 break-all">{mSkill.externalCommand}</p>
          )}
          <p className="text-[12px] text-cyan-400/60">
            This skill runs as an external CLI agent.
          </p>
        </div>
      )}

      {mSkill?.requiresSetup && mSkill.setupNote && (
        <div className="p-4 bg-purple-500/5 border border-purple-500/10 rounded-2xl">
          <span className="flex items-center gap-1.5 text-xs font-bold uppercase text-purple-400 mb-2">
            <Wrench size={12} /> Setup Required
          </span>
          <p className="text-sm text-purple-200/70 leading-relaxed">{mSkill.setupNote}</p>
        </div>
      )}

      {mSkill?.requiresApiKey && mSkill.apiKeyEnv && (
        <div className="p-4 bg-amber-500/5 border border-amber-500/10 rounded-2xl space-y-3">
          <div className="flex items-center gap-1.5">
            <Key size={12} className="text-amber-400" />
            <span className="text-xs font-bold uppercase text-amber-400">API Key Required</span>
          </div>
          <p className="text-sm text-amber-300/70">
            Requires <strong>{mSkill.apiKeyEnv}</strong>
            {mSkill.apiKeyUrl && (
              <> &mdash; <a href={mSkill.apiKeyUrl} target="_blank" rel="noopener" className="underline hover:text-amber-200">get API key</a></>
            )}
          </p>
          {savedKeys[mSkill.apiKeyEnv] ? (
            <span className="flex items-center gap-1 text-sm text-green-400"><CheckCircle size={14} /> {t.keyConfigured || 'Key configured'}</span>
          ) : (
            <div className="flex items-center gap-2">
              <input
                type="password"
                value={keyInputs[mSkill.apiKeyEnv] || ''}
                onChange={e => setKeyInputs(prev => ({ ...prev, [mSkill.apiKeyEnv]: e.target.value }))}
                placeholder="sk-..."
                className="flex-1 px-3 py-2 bg-white/10 border border-amber-500/20 rounded-xl text-white text-sm placeholder:text-white/35 focus:outline-none focus:border-amber-500/50"
              />
              <Button
                onClick={() => handleSaveKey(mSkill.apiKeyEnv!, keyInputs[mSkill.apiKeyEnv!] || '')}
                disabled={savingKey === mSkill.apiKeyEnv || !keyInputs[mSkill.apiKeyEnv!]?.trim()}
                className="shrink-0 px-4 py-2 bg-amber-500/20 hover:bg-amber-500/30 text-amber-400 text-xs font-bold rounded-xl disabled:opacity-40"
              >
                {savingKey === mSkill.apiKeyEnv ? <RefreshCw size={12} className="animate-spin" /> : 'Save'}
              </Button>
            </div>
          )}
        </div>
      )}

      {mSkill && (mSkill.npmPackage || mSkill.repoUrl) && (
        <div className="flex items-center gap-3 text-xs">
          {mSkill.npmPackage && (
            <a href={`https://www.npmjs.com/package/${mSkill.npmPackage}`} target="_blank" rel="noopener" className="flex items-center gap-1 text-cyan-400 hover:underline">
              <ExternalLink size={10} /> npm
            </a>
          )}
          {mSkill.repoUrl && (
            <a href={mSkill.repoUrl} target="_blank" rel="noopener" className="flex items-center gap-1 text-purple-400 hover:underline">
              <ExternalLink size={10} /> GitHub
            </a>
          )}
        </div>
      )}

      {!isMarketSkill && detailSkill && (
        <div className="flex items-center gap-2 flex-wrap">
          {detailSkill.autoGenerated && (
            <span className="px-2 py-0.5 bg-emerald-500/10 rounded-full text-xs text-emerald-400 font-bold">{t.autoGenerated || 'Auto-generated'}</span>
          )}
          {detailSkill.connected && (
            <span className="px-2 py-0.5 bg-green-500/10 rounded-full text-xs text-green-400 font-bold">{t.connected || 'Connected'}</span>
          )}
          <span className={`px-2 py-0.5 rounded-full text-xs font-bold ${
            detailSkill.enabled ? 'bg-green-500/10 text-green-400' : 'bg-white/5 text-white/45'
          }`}>
            {detailSkill.enabled ? (t.enabled || 'Enabled') : (t.disabled || 'Disabled')}
          </span>
        </div>
      )}

      <div className="flex items-center gap-3 pt-2 border-t border-white/5">
        {mSkill && isMarketSkill ? (
          <Button
            onClick={() => { handleInstall(mSkill); setDetailSkill(null); }}
            disabled={mSkill.installed || installing === mSkill.id}
            className={`text-xs font-bold px-5 py-2.5 h-auto rounded-xl ${
              mSkill.installed
                ? 'bg-green-500/20 text-green-400 cursor-default'
                : 'bg-celestial-saturn text-black hover:scale-105'
            }`}
          >
            {mSkill.installed ? (
              <><CheckCircle size={14} className="mr-1" /> {t.installedStatus || 'Installed'}</>
            ) : installing === mSkill.id ? (
              <><RefreshCw size={14} className="mr-1 animate-spin" /> {t.installingStatus || 'Installing...'}</>
            ) : (
              <><Download size={14} className="mr-1" /> {t.installBtn || 'Install'}</>
            )}
          </Button>
        ) : detailSkill ? (
          <>
            <button
              onClick={() => handleToggle(detailSkill.name, !detailSkill.enabled)}
              className={`flex items-center gap-1.5 px-4 py-2 rounded-xl text-xs font-bold transition-colors ${
                detailSkill.enabled
                  ? 'text-white/55 hover:bg-white/5'
                  : 'text-green-400 bg-green-500/10 hover:bg-green-500/20'
              }`}
            >
              {detailSkill.enabled ? <PowerOff size={13} /> : <Power size={13} />}
              {detailSkill.enabled ? 'Disable' : 'Enable'}
            </button>
            <button
              onClick={() => { handleUninstall(detailSkill.name); setDetailSkill(null); }}
              className="flex items-center gap-1.5 px-4 py-2 rounded-xl text-xs font-bold text-red-400 bg-red-500/10 hover:bg-red-500/20 transition-colors"
            >
              <Trash2 size={13} /> Uninstall
            </button>
          </>
        ) : null}
      </div>
    </motion.div>
  );
}
