/**
 * Gaea Skill Management Tools — generate, list, and install MCP skills.
 *
 * These tools let the LLM agent create new reusable tools from natural language
 * descriptions, inspect existing skills, and install skill packages from disk.
 */
import { ToolRegistry } from '../registry';
import { generateSkill } from '../../skills/generator';
import { mcpManager } from '../../mcp/client';

// Module-level LLM getters, set during registration
let _llmGetters: {
  getDeepSeek: () => any;
  getGemini?: () => any;
  getOpenAI?: () => any;
  getAnthropic?: () => any;
  getQwen?: () => any;
  getOllama?: () => any;
  getLmStudio?: () => any;
} | null = null;

export function setSkillLLMGetters(getters: typeof _llmGetters): void {
  _llmGetters = getters;
}

async function generateSkillHandler(args: Record<string, any>): Promise<string> {
  if (!_llmGetters) {
    return 'Skill generation is not available: LLM providers have not been initialized yet. The server may still be starting up.';
  }

  const description = String(args.description || '').trim();
  if (!description) {
    return 'Error: Please provide a description of what the skill should do. Be specific about inputs, processing logic, and expected output.';
  }

  const provider = (args.provider as string) || 'deepseek';
  const model = (args.model as string) || 'deepseek-chat';

  const result = await generateSkill(
    {
      description,
      provider: provider as any,
      model,
    },
    _llmGetters.getDeepSeek,
    _llmGetters.getGemini,
    _llmGetters.getOpenAI,
    _llmGetters.getAnthropic,
    _llmGetters.getQwen,
  );

  if (!result.success) {
    return `Skill generation failed: ${result.error || 'Unknown error'}`;
  }

  let response = `Skill "${result.skillName}" generated successfully.\n`;
  response += `Directory: ${result.directory}\n`;
  response += `Tool name: ${result.toolName}\n`;

  if (result.error) {
    response += `\nWarnings: ${result.error}\n`;
  }

  response += `\nThe skill is ready at ${result.directory}. Use install_skill to register it, or it will be auto-installed on next server restart.`;
  return response;
}

async function listSkillsHandler(): Promise<string> {
  try {
    const skills = mcpManager.listLocalSkills();
    if (skills.length === 0) {
      return 'No locally installed skills found in ~/gaea_skills/. Generate one with the generate_skill tool.';
    }

    const lines = skills.map(s => {
      const autoBadge = s.autoGenerated ? '[auto]' : '[manual]';
      return `- **${s.name}** ${autoBadge}: ${s.description} (${s.toolCount} tool(s), installed ${s.installedAt.slice(0, 10)})`;
    });

    return `Installed skills (${skills.length} total):\n\n${lines.join('\n')}`;
  } catch (err: any) {
    return `Failed to list skills: ${err.message}`;
  }
}

async function installSkillHandler(args: Record<string, any>): Promise<string> {
  const dir = String(args.directory || '').trim();
  if (!dir) {
    return 'Error: "directory" parameter is required. Provide the absolute path to the skill directory containing index.ts and package.json.';
  }

  const name = String(args.name || '').trim() || dir.split(/[/\\]/).pop() || 'unknown';

  try {
    const destDir = mcpManager.installSkill(name, dir);
    return `Skill "${name}" installed successfully at ${destDir}. It will be available as a tool after reconnecting MCP servers (or on next server restart).`;
  } catch (err: any) {
    return `Install failed: ${err.message}. The skill may already be installed — check with list_skills.`;
  }
}

export function registerSkillTools(registry: ToolRegistry): void {
  registry.register({
    name: 'generate_skill',
    description:
      'Generate a new reusable MCP skill (tool) from a natural language description. ' +
      'The skill becomes a standalone MCP server with a fully implemented handler function. ' +
      'Use this when you notice a repeating workflow pattern or when the user asks for automation. ' +
      'The generated skill will be available as mcp_{skillName}_{toolName} after installation.',
    parameters: {
      type: 'object',
      properties: {
        description: {
          type: 'string',
          description:
            'Natural language description of what the skill should do. Be specific: describe the inputs, the processing logic, error handling, and expected output format.',
        },
        provider: {
          type: 'string',
          description: 'LLM provider to use for code generation. Default: deepseek.',
          enum: ['deepseek', 'qwen', 'openai', 'gemini', 'anthropic'],
        },
        model: {
          type: 'string',
          description: 'Specific model name. Default: deepseek-chat.',
        },
      },
      required: ['description'],
    },
    handler: generateSkillHandler,
    permission: 'user',
    securityLevel: 'confirm',
  });

  registry.register({
    name: 'list_skills',
    description:
      'List all locally installed MCP skills in ~/gaea_skills/. ' +
      'Shows skill name, description, tool count, and whether it was auto-generated. ' +
      'Use before generating new skills to check for duplicates.',
    parameters: {
      type: 'object',
      properties: {},
      required: [],
    },
    handler: listSkillsHandler,
    permission: 'public',
    securityLevel: 'safe',
  });

  registry.register({
    name: 'install_skill',
    description:
      'Install an MCP skill from a local directory into ~/gaea_skills/ so it becomes available as a tool. ' +
      'The directory must contain index.ts and package.json for a valid MCP server.',
    parameters: {
      type: 'object',
      properties: {
        directory: {
          type: 'string',
          description: 'Absolute path to the skill directory containing index.ts and package.json.',
        },
        name: {
          type: 'string',
          description: 'Skill name. Defaults to the directory basename.',
        },
      },
      required: ['directory'],
    },
    handler: installSkillHandler,
    permission: 'user',
    securityLevel: 'confirm',
  });
}
