// Polyfill WebSocket for Node.js (required by MCP SDK's WebSocket transport)
import { WebSocket } from 'ws';
globalThis.WebSocket = WebSocket as any;

import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { StdioClientTransport } from '@modelcontextprotocol/sdk/client/stdio.js';
import { StreamableHTTPClientTransport } from '@modelcontextprotocol/sdk/client/streamableHttp.js';
import { WebSocketClientTransport } from '@modelcontextprotocol/sdk/client/websocket.js';
import fs from 'fs';
import path from 'path';
import os from 'os';
import { exec, execFile } from 'child_process';
import { getDataPath } from '../config/data_path';

export interface MCPServerConfig {
  command?: string;
  args?: string[];
  env?: Record<string, string>;
  enabled: boolean;
  source?: 'local' | 'external';      // local = Gaea skill dir, external = third-party
  transport?: 'stdio' | 'http' | 'ws'; // stdio = local process, http = HTTP, ws = WebSocket
  url?: string;                         // URL for remote MCP server (http/ws transport)
  headers?: Record<string, string>;    // custom auth headers for remote connection
  autoGenerated?: boolean;             // true if Gaea generated this skill
  generatedFrom?: string;              // trace: conversation ID or workflow ID
  description?: string;                // human-readable description
  toolCount?: number;                  // cached tool count for UI
}

export interface MCPToolDef {
  serverName: string;
  name: string;
  description?: string;
  inputSchema: Record<string, any>;
}

export interface SkillPackage {
  name: string;          // directory name / skill id
  description: string;
  toolCount: number;
  autoGenerated: boolean;
  generatedFrom?: string;
  installedAt: string;
  source: 'local' | 'external';
  broken?: boolean;       // dir exists but no index.ts — can be auto-cleaned on reinstall
}

interface ConnectedServer {
  client: Client;
  transport: StdioClientTransport | StreamableHTTPClientTransport | WebSocketClientTransport;
  config: MCPServerConfig;
}

const SKILLS_DIR = path.join(os.homedir(), 'gaea_skills');

function expandPortablePath(value: string): string {
  if (value === '~') return os.homedir();
  if (value.startsWith('~/') || value.startsWith('~\\')) {
    return path.join(os.homedir(), value.slice(2));
  }
  return value.replace(/\$\{GAEA_SKILLS_DIR\}/g, SKILLS_DIR);
}

function toPortableSkillPath(filePath: string): string {
  const relative = path.relative(SKILLS_DIR, filePath);
  if (relative && !relative.startsWith('..') && !path.isAbsolute(relative)) {
    return `~/gaea_skills/${relative.split(path.sep).join('/')}`;
  }
  return filePath;
}

interface CrashTracker {
  consecutiveCrashes: number;
  lastCrashTime: string;
  lastSuccessfulConnect: string;
  restartTimer: ReturnType<typeof setTimeout> | null;
}

class MCPClientManager {
  private servers: Map<string, ConnectedServer> = new Map();
  private configPath: string;
  private crashTrackers: Map<string, CrashTracker> = new Map();
  private closingSet: Set<string> = new Set();
  private onServerRecovered?: (name: string, tools: MCPToolDef[]) => void;
  private ioRef?: any;

  constructor(configPath?: string) {
    this.configPath = configPath || path.join(process.cwd(), 'server', 'mcp', 'config.json');
  }

  setSocketIO(io: any): void { this.ioRef = io; }
  setOnServerRecovered(cb: (name: string, tools: MCPToolDef[]) => void): void { this.onServerRecovered = cb; }

  getConfig(): Record<string, MCPServerConfig> {
    try {
      let raw = fs.readFileSync(this.configPath, 'utf-8');
      // Replace static relative paths with actual data directory paths
      raw = raw.replace(/"data\/lumi\.db"/g, JSON.stringify(getDataPath('gaea.db')));
      const parsed = JSON.parse(raw);
      return parsed.mcpServers || {};
    } catch {
      return {};
    }
  }

  saveConfig(servers: Record<string, MCPServerConfig>): void {
    const dir = path.dirname(this.configPath);
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
    fs.writeFileSync(this.configPath, JSON.stringify({ mcpServers: servers }, null, 2));
  }

  // ── Local skill directory management ──

  /** Ensure the skills directory exists */
  private ensureSkillsDir(): void {
    if (!fs.existsSync(SKILLS_DIR)) {
      fs.mkdirSync(SKILLS_DIR, { recursive: true });
    }
  }

  /** List all local skills in ~/gaea_skills/ */
  listLocalSkills(): SkillPackage[] {
    this.ensureSkillsDir();
    const skills: SkillPackage[] = [];
    const entries = fs.readdirSync(SKILLS_DIR, { withFileTypes: true });

    for (const entry of entries) {
      if (!entry.isDirectory()) continue;
      const skillDir = path.join(SKILLS_DIR, entry.name);
      const pkgPath = path.join(skillDir, 'package.json');
      const indexPath = path.join(skillDir, 'index.ts');

      let pkg: any = {};
      try { pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf-8')); } catch {}

      const hasIndex = fs.existsSync(indexPath);
      const hasRunCommand = !!pkg.gaea?.runCommand;
      const broken = !hasIndex && !hasRunCommand;

      skills.push({
        name: entry.name,
        description: pkg.description || pkg.gaea?.description || entry.name,
        toolCount: pkg.gaea?.toolCount || 0,
        autoGenerated: pkg.gaea?.autoGenerated || false,
        generatedFrom: pkg.gaea?.generatedFrom,
        installedAt: pkg.gaea?.installedAt || '',
        source: 'local',
        broken,
      });
    }
    return skills;
  }

  /** Install a skill from a source directory into ~/gaea_skills/ */
  installSkill(name: string, sourceDir: string, allowUpgrade = false): string {
    this.ensureSkillsDir();
    const destDir = path.join(SKILLS_DIR, name);

    if (fs.existsSync(destDir)) {
      const hasIndex = fs.existsSync(path.join(destDir, 'index.ts'));
      const pkg = this.readPkg(destDir);
      const hasRunCmd = !!pkg.gaea?.runCommand;
      if (!hasIndex && !hasRunCmd) {
        fs.rmSync(destDir, { recursive: true, force: true });
      } else if (allowUpgrade) {
        // Check if source is newer than installed
        const srcPkg = this.readPkg(sourceDir);
        const srcVersion = srcPkg.version || '0.0.0';
        const installedVersion = pkg.gaea?.installedVersion || '0.0.0';
        if (srcVersion === installedVersion) {
          return destDir; // Already up to date
        }
        console.log(`[MCP] Upgrading "${name}" ${installedVersion} → ${srcVersion}`);
        fs.rmSync(destDir, { recursive: true, force: true });
      } else {
        throw new Error(`Skill "${name}" already exists. Uninstall it first.`);
      }
    }

    this.copyDirSync(sourceDir, destDir);
    this.installDepsInDir(destDir);
    this.patchInstalledMetadata(destDir);
    // Also stamp the installed version from source
    const srcPkg = this.readPkg(sourceDir);
    this.patchInstalledVersion(destDir, srcPkg.version || '0.0.0');

    const resultingPkg: any = this.readPkg(destDir);
    this.registerLocalSkill(name, destDir, resultingPkg);

    return destDir;
  }

  /** Check if a bundled source has a newer version than the installed copy */
  isUpgradeAvailable(name: string, sourceDir: string): boolean {
    const destDir = path.join(SKILLS_DIR, name);
    if (!fs.existsSync(destDir)) return false;
    const destPkg = this.readPkg(destDir);
    const srcPkg = this.readPkg(sourceDir);
    const srcVersion = srcPkg.version || '0.0.0';
    const installedVersion = destPkg.gaea?.installedVersion || destPkg.version || '0.0.0';
    return srcVersion !== installedVersion;
  }

  /** Install a skill from an npm package (e.g. "gaea-skill-nanobanana") */
  async installFromNpm(packageName: string): Promise<string> {
    this.ensureSkillsDir();
    const skillName = packageName
      .replace(/^@/, '')
      .replace(/\//g, '-')
      .replace(/[^a-z0-9-]/g, '-');
    const skillDir = path.join(SKILLS_DIR, skillName);

    if (fs.existsSync(skillDir)) {
      const hasIndex = fs.existsSync(path.join(skillDir, 'index.ts'));
      const pkg = this.readPkg(skillDir);
      const hasRunCmd = !!pkg.gaea?.runCommand;
      if (!hasIndex && !hasRunCmd) {
        fs.rmSync(skillDir, { recursive: true, force: true });
      } else {
        throw new Error(`Skill "${skillName}" already exists. Uninstall it first.`);
      }
    }

    // Create a workspace package that depends on the npm MCP skill
    fs.mkdirSync(skillDir, { recursive: true });
    const workspacePkg: any = {
      name: `gaea-skill-${skillName}`,
      version: '1.0.0',
      type: 'module',
      description: `Installed from npm: ${packageName}`,
      dependencies: { [packageName]: '*' },
      gaea: { installedAt: new Date().toISOString(), installedFrom: 'npm', npmPackage: packageName },
    };
    fs.writeFileSync(path.join(skillDir, 'package.json'), JSON.stringify(workspacePkg, null, 2));

    // npm install — the dep gets resolved into node_modules/{packageName}
    await this.installDepsSync(skillDir);

    // Read the installed package's package.json for gaea config
    const depPkgPath = path.join(skillDir, 'node_modules', ...packageName.split('/'), 'package.json');
    let depPkg: any = {};
    try { depPkg = JSON.parse(fs.readFileSync(depPkgPath, 'utf-8')); } catch {}

    const skillCfg = depPkg.gaea || {};

    if (skillCfg.runCommand) {
      // External MCP with its own run command — use directly
      workspacePkg.gaea.runCommand = skillCfg.runCommand;
      workspacePkg.gaea.runArgs = skillCfg.runArgs || [];
      workspacePkg.gaea.toolCount = skillCfg.toolCount || 0;
      workspacePkg.gaea.requiresApiKey = skillCfg.requiresApiKey || false;
      workspacePkg.gaea.apiKeyEnv = skillCfg.apiKeyEnv;
      workspacePkg.gaea.apiKeyUrl = skillCfg.apiKeyUrl;
      workspacePkg.gaea.description = depPkg.description || skillCfg.description || packageName;
      fs.writeFileSync(path.join(skillDir, 'package.json'), JSON.stringify(workspacePkg, null, 2));
      this.registerLocalSkill(skillName, skillDir, workspacePkg);
    } else if (depPkg.main || depPkg.exports || fs.existsSync(path.join(path.dirname(depPkgPath), 'index.mjs'))) {
      // Standard MCP package: create a tsx wrapper index.ts
      const wrapper = `// Auto-generated wrapper for npm package: ${packageName}
import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js';

async function main() {
  // The npm package exports its own MCP server — import and start
  const mod = await import('${packageName}');
  // If the package exports a server directly, use it; otherwise start via the package's main
  if (mod.server) {
    const transport = new StdioServerTransport();
    await mod.server.connect(transport);
    console.error('[npm-skill] ${packageName} ready');
  } else if (mod.default?.server) {
    const transport = new StdioServerTransport();
    await mod.default.server.connect(transport);
    console.error('[npm-skill] ${packageName} ready (default export)');
  } else {
    // Fallback: let the package's entry point handle it (it should be self-booting)
    console.error('[npm-skill] ${packageName} loaded (self-booting)');
  }
}
main().catch((err) => { console.error('[npm-skill] Fatal:', err); process.exit(1); });
`;
      fs.writeFileSync(path.join(skillDir, 'index.ts'), wrapper);
      workspacePkg.gaea.toolCount = skillCfg.toolCount || 1;
      workspacePkg.gaea.description = depPkg.description || skillCfg.description || packageName;
      workspacePkg.dependencies = workspacePkg.dependencies || {};
      workspacePkg.dependencies['@modelcontextprotocol/sdk'] = '^1.0.0';
      fs.writeFileSync(path.join(skillDir, 'package.json'), JSON.stringify(workspacePkg, null, 2));
      await this.installDepsSync(skillDir);
      this.registerLocalSkill(skillName, skillDir, workspacePkg);
    } else {
      throw new Error(`npm package "${packageName}" does not have a lumi MCP config (skillCfg.runCommand or main entry). Not a valid Gaea skill package.`);
    }

    return skillDir;
  }

  /** Install a skill from a GitHub repository (clone + npm install + register) */
  async installFromGitHub(repoUrl: string): Promise<string> {
    this.ensureSkillsDir();
    const repoName = repoUrl
      .split('/').pop()!
      .replace(/\.git$/, '')
      .replace(/[^a-zA-Z0-9-]/g, '-')
      .toLowerCase();
    const skillDir = path.join(SKILLS_DIR, repoName);

    if (fs.existsSync(skillDir)) {
      const hasIndex = fs.existsSync(path.join(skillDir, 'index.ts'));
      const pkg = this.readPkg(skillDir);
      const hasRunCmd = !!pkg.gaea?.runCommand;
      if (!hasIndex && !hasRunCmd) {
        fs.rmSync(skillDir, { recursive: true, force: true });
      } else {
        throw new Error(`Skill "${repoName}" already exists. Uninstall it first.`);
      }
    }

    // Validate repo URL to prevent command injection
    const GITHUB_URL_RE = /^https:\/\/github\.com\/[\w.-]+\/[\w.-]+(\.git)?$/;
    if (!GITHUB_URL_RE.test(repoUrl)) {
      throw new Error(`Invalid GitHub repository URL: ${repoUrl}. Only https://github.com/owner/repo is allowed.`);
    }

    console.log(`[MCP] Cloning ${repoUrl} → ${skillDir}`);
    await new Promise<void>((resolve, reject) => {
      execFile('git', ['clone', '--depth', '1', repoUrl, skillDir], { timeout: 60000 }, (err) => {
        err ? reject(new Error(`Git clone failed: ${err.message}`)) : resolve();
      });
    });

    // Run npm install
    await this.installDepsSync(skillDir);

    // Read package.json for gaea config
    let pkg: any = this.readPkg(skillDir);
    const skillCfg = pkg.gaea || {};

    // Patch install metadata
    if (!pkg.gaea) pkg.gaea = {};
    pkg.gaea.installedAt = new Date().toISOString();
    pkg.gaea.installedFrom = 'github';
    pkg.gaea.repoUrl = repoUrl;
    pkg.gaea.toolCount = skillCfg.toolCount || 1;
    if (!pkg.description) pkg.description = skillCfg.description || repoName;
    fs.writeFileSync(path.join(skillDir, 'package.json'), JSON.stringify(pkg, null, 2));

    this.registerLocalSkill(repoName, skillDir, pkg);
    return skillDir;
  }

  /** Run npm install synchronously (awaits completion) */
  private installDepsSync(dir: string): Promise<void> {
    return new Promise((resolve, reject) => {
      exec('npm install --loglevel=error --no-audit --no-fund', {
        timeout: 120000,
        cwd: dir,
      }, (error, _stdout, stderr) => {
        if (error) {
          console.warn(`[MCP] npm install failed in ${path.basename(dir)}:`, stderr.trim() || error.message);
          reject(new Error(stderr.trim() || error.message));
        } else {
          console.log(`[MCP] Dependencies installed in ${path.basename(dir)}`);
          resolve();
        }
      });
    });
  }

  private readPkg(dir: string): any {
    const pkgPath = path.join(dir, 'package.json');
    try { return JSON.parse(fs.readFileSync(pkgPath, 'utf-8')); } catch { return {}; }
  }

  private patchInstalledMetadata(dir: string): void {
    const pkgPath = path.join(dir, 'package.json');
    let pkg: any = {};
    try { pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf-8')); } catch {}
    if (!pkg.gaea) pkg.gaea = {};
    pkg.gaea.installedAt = new Date().toISOString();
    pkg.gaea.autoGenerated = pkg.gaea.autoGenerated || false;
    fs.writeFileSync(pkgPath, JSON.stringify(pkg, null, 2));
  }

  /** Stamp the source version onto the installed copy so we can detect upgrades */
  private patchInstalledVersion(dir: string, version: string): void {
    const pkgPath = path.join(dir, 'package.json');
    let pkg: any = {};
    try { pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf-8')); } catch {}
    if (!pkg.gaea) pkg.gaea = {};
    pkg.gaea.installedVersion = version;
    fs.writeFileSync(pkgPath, JSON.stringify(pkg, null, 2));
  }

  /** Uninstall a local skill */
  uninstallSkill(name: string): void {
    const skillDir = path.join(SKILLS_DIR, name);
    if (fs.existsSync(skillDir)) {
      fs.rmSync(skillDir, { recursive: true, force: true });
    }

    // Remove from config.json
    const config = this.getConfig();
    if (config[name]) {
      delete config[name];
      this.saveConfig(config);
    }
  }

  /** Register a skill directory as an MCP server entry in config.json */
  private registerLocalSkill(name: string, skillDir: string, pkg: any): void {
    const config = this.getConfig();
    const skillCfg = pkg.gaea || {};

    // Support external MCP packages with custom run commands
    if (skillCfg.runCommand) {
      config[name] = {
        command: skillCfg.runCommand,
        args: skillCfg.runArgs || [],
        env: skillCfg.requiresApiKey && skillCfg.apiKeyEnv
          ? { [skillCfg.apiKeyEnv]: `\${${skillCfg.apiKeyEnv}}` }
          : undefined,
        enabled: !skillCfg.requiresApiKey, // Disable by default if API key needed
        source: 'local',
        transport: 'stdio',
        autoGenerated: skillCfg.autoGenerated || false,
        generatedFrom: skillCfg.generatedFrom,
        description: pkg.description || skillCfg.description || name,
        toolCount: skillCfg.toolCount,
      };
    } else {
      const indexPath = toPortableSkillPath(path.join(skillDir, 'index.ts'));
      // Build env map from skillCfg.envKeys (array of key names to pass through from stored keys)
      let env: Record<string, string> | undefined;
      if (skillCfg.envKeys && Array.isArray(skillCfg.envKeys)) {
        env = {};
        for (const k of skillCfg.envKeys) { env[k] = `\${${k}}`; }
      }
      config[name] = {
        command: 'npx',
        args: ['tsx', indexPath],
        env,
        enabled: true,
        source: 'local',
        autoGenerated: skillCfg.autoGenerated || false,
        generatedFrom: skillCfg.generatedFrom,
        description: pkg.description || skillCfg.description || name,
        toolCount: skillCfg.toolCount,
      };
    }

    this.saveConfig(config);
  }

  /** Run npm install in a skill directory (fire-and-forget, non-blocking) */
  private installDepsInDir(dir: string): void {
    exec('npm install --loglevel=error --no-audit --no-fund', {
      timeout: 120000,
      cwd: dir,
    }, (error, _stdout, stderr) => {
      if (error) {
        console.warn(`[MCP] npm install failed in ${dir}:`, stderr.trim() || error.message);
      } else {
        console.log(`[MCP] Dependencies installed in ${path.basename(dir)}`);
      }
    });
  }

  private copyDirSync(src: string, dest: string): void {
    if (!fs.existsSync(dest)) fs.mkdirSync(dest, { recursive: true });
    const entries = fs.readdirSync(src, { withFileTypes: true });
    for (const entry of entries) {
      const srcPath = path.join(src, entry.name);
      const destPath = path.join(dest, entry.name);
      if (entry.isDirectory()) {
        if (entry.name === 'node_modules') continue; // skip, will be installed by user
        this.copyDirSync(srcPath, destPath);
      } else {
        fs.copyFileSync(srcPath, destPath);
      }
    }
  }

  // ── MCP Server connection management ──

  async connectAll(): Promise<MCPToolDef[]> {
    // Scan local skills directory and register any unregistered skills
    this.ensureSkillsDir();
    const localEntries = fs.existsSync(SKILLS_DIR)
      ? fs.readdirSync(SKILLS_DIR, { withFileTypes: true })
      : [];
    const config = this.getConfig();

    for (const entry of localEntries) {
      if (!entry.isDirectory()) continue;
      const skillDir = path.join(SKILLS_DIR, entry.name);
      const indexPath = path.join(skillDir, 'index.ts');
      if (!fs.existsSync(indexPath)) continue;

      if (!config[entry.name]) {
        let pkg: any = {};
        try {
          pkg = JSON.parse(fs.readFileSync(path.join(skillDir, 'package.json'), 'utf-8'));
        } catch {}
        this.registerLocalSkill(entry.name, skillDir, pkg);
      }
    }

    // Reload config after auto-registering local skills
    const finalConfig = this.getConfig();
    const allTools: MCPToolDef[] = [];

    for (const [serverName, serverConfig] of Object.entries(finalConfig)) {
      if (!serverConfig.enabled) continue;

      try {
        const tools = await this.connectServer(serverName, serverConfig);
        allTools.push(...tools);

        // Update toolCount in config
        if (serverConfig.source === 'local' && serverConfig.toolCount !== tools.length) {
          serverConfig.toolCount = tools.length;
          this.saveConfig(finalConfig);
        }

        console.log(`[MCP] ${serverName}: ${tools.length} tools discovered (${serverConfig.source || 'external'})`);
      } catch (err: any) {
        console.warn(`[MCP] Failed to connect to ${serverName}: ${err.message}`);
      }
    }

    return allTools;
  }

  private async connectServer(name: string, config: MCPServerConfig): Promise<MCPToolDef[]> {
    // Dedup: if already connected, return cached tools
    const existing = this.servers.get(name);
    if (existing) {
      try {
        const tools = await existing.client.listTools();
        return tools.tools.map((tool: any) => ({
          serverName: name,
          name: `mcp_${name}_${tool.name}`,
          description: tool.description || `${tool.name} (from MCP server: ${name})`,
          inputSchema: tool.inputSchema || { type: 'object', properties: {} },
        }));
      } catch {
        // Stale connection — clean up and reconnect below
        this.servers.delete(name);
      }
    }

    const transportType = config.transport || (config.url ? (config.url.startsWith('wss://') || config.url.startsWith('ws://') ? 'ws' : 'http') : 'stdio');
    let transport: StdioClientTransport | StreamableHTTPClientTransport | WebSocketClientTransport;

    if (transportType === 'ws' && config.url) {
      transport = new WebSocketClientTransport(new URL(config.url));
    } else if (transportType === 'http' && config.url) {
      transport = new StreamableHTTPClientTransport(
        new URL(config.url),
        {
          requestInit: config.headers ? { headers: config.headers } : undefined,
        },
      );
    } else if (config.command) {
      // Expand ${VAR_NAME} placeholders in env values using process.env + stored keys
      const storedKeys: Record<string, string> = {};
      try {
        const { loadKeys } = require('../config/keys');
        Object.assign(storedKeys, loadKeys());
      } catch {}
      const resolvedEnv: Record<string, string> = {};
      if (config.env) {
        for (const [k, v] of Object.entries(config.env)) {
          resolvedEnv[k] = v.replace(/\$\{(\w+)\}/g, (_, name) => process.env[name] || storedKeys[name] || '');
        }
      }
      transport = new StdioClientTransport({
        command: expandPortablePath(config.command),
        args: (config.args || []).map(arg => expandPortablePath(arg)),
        env: Object.keys(resolvedEnv).length > 0 ? resolvedEnv : (config.env || undefined),
      });
    } else {
      throw new Error(`MCP server "${name}": must provide "url" for http/ws transport or "command" for stdio transport`);
    }

    const client = new Client(
      { name: 'gaeaOS-mcp-client', version: '2.0' },
      { capabilities: {} },
    );

    await client.connect(transport);

    this.servers.set(name, { client, transport, config });

    // Initialize crash tracker
    if (!this.crashTrackers.has(name)) {
      this.crashTrackers.set(name, {
        consecutiveCrashes: 0,
        lastCrashTime: '',
        lastSuccessfulConnect: new Date().toISOString(),
        restartTimer: null,
      });
    }

    // Install crash detection on transport
    const self = this;
    transport.onclose = () => {
      // If intentionally closing, skip crash detection
      if (self.closingSet.has(name)) {
        self.closingSet.delete(name);
        return;
      }
      // If server still in map, this is an unexpected crash
      if (self.servers.has(name)) {
        console.log(`[MCP] CRASH DETECTED: "${name}" process exited unexpectedly`);
        self.servers.delete(name);
        const tracker = self.crashTrackers.get(name);
        if (tracker) {
          tracker.lastCrashTime = new Date().toISOString();
        }
        self.scheduleRestart(name);
        self.broadcastHealth();
      }
    };

    transport.onerror = (error: Error) => {
      console.error(`[MCP] Error in "${name}" transport:`, error.message);
    };

    // Reset crash counter on successful connect
    const tracker = self.crashTrackers.get(name)!;
    tracker.consecutiveCrashes = 0;
    tracker.lastSuccessfulConnect = new Date().toISOString();
    if (tracker.restartTimer) {
      clearTimeout(tracker.restartTimer);
      tracker.restartTimer = null;
    }

    const result = await client.listTools();
    return result.tools.map((tool: any) => ({
      serverName: name,
      name: `mcp_${name}_${tool.name}`,
      description: tool.description || `${tool.name} (from MCP server: ${name})`,
      inputSchema: tool.inputSchema || { type: 'object', properties: {} },
    }));
  }

  async callTool(fullName: string, args: Record<string, any>): Promise<string> {
    const match = fullName.match(/^mcp_(.+?)_(.+)$/);
    if (!match) throw new Error(`Invalid MCP tool name: ${fullName}`);

    const [, serverName, toolName] = match;
    const server = this.servers.get(serverName);
    if (!server) throw new Error(`MCP server "${serverName}" not connected`);

    const result = await server.client.callTool({ name: toolName, arguments: args });

    const contents = (result as any).content || [];
    return contents
      .filter((c: any) => c.type === 'text')
      .map((c: any) => c.text)
      .join('\n');
  }

  async disconnectAll(): Promise<void> {
    // Cancel all pending restart timers
    for (const [n, tracker] of this.crashTrackers) {
      if (tracker.restartTimer) {
        clearTimeout(tracker.restartTimer);
        tracker.restartTimer = null;
      }
    }
    for (const [name, server] of this.servers) {
      this.closingSet.add(name);
      try {
        await server.transport.close();
      } catch {}
    }
    this.servers.clear();
    this.closingSet.clear();
  }

  async restartServer(name: string): Promise<MCPToolDef[]> {
    const server = this.servers.get(name);
    if (server) {
      this.closingSet.add(name);
      try { await server.transport.close(); } catch {}
      this.servers.delete(name);
      this.closingSet.delete(name);
    }

    const config = this.getConfig();
    const serverConfig = config[name];
    if (!serverConfig || !serverConfig.enabled) return [];

    return this.connectServer(name, serverConfig);
  }

  /** Disconnect a server without restarting it (used when disabling) */
  async disconnectServer(name: string): Promise<void> {
    const server = this.servers.get(name);
    if (server) {
      this.closingSet.add(name);
      try { await server.transport.close(); } catch {}
      this.servers.delete(name);
      this.closingSet.delete(name);
    }
  }

  private scheduleRestart(name: string): void {
    const tracker = this.crashTrackers.get(name);
    if (!tracker) return;

    if (tracker.restartTimer) {
      clearTimeout(tracker.restartTimer);
    }

    // Max 5 consecutive crashes before giving up
    if (tracker.consecutiveCrashes >= 5) {
      console.error(`[MCP] "${name}" crashed ${tracker.consecutiveCrashes} times — giving up. Manual intervention required.`);
      return;
    }

    const delay = Math.min(1000 * Math.pow(2, tracker.consecutiveCrashes), 60000);
    tracker.consecutiveCrashes++;

    console.log(`[MCP] Scheduling restart for "${name}" in ${delay}ms (crash #${tracker.consecutiveCrashes})`);

    tracker.restartTimer = setTimeout(async () => {
      tracker.restartTimer = null;
      try {
        const config = this.getConfig();
        const serverConfig = config[name];
        if (!serverConfig || !serverConfig.enabled) {
          console.log(`[MCP] Server "${name}" is now disabled, skipping restart`);
          return;
        }

        const tools = await this.connectServer(name, serverConfig);
        console.log(`[MCP] "${name}" restarted successfully with ${tools.length} tools`);

        tracker.consecutiveCrashes = 0;
        tracker.lastSuccessfulConnect = new Date().toISOString();

        this.onServerRecovered?.(name, tools);
      } catch (err: any) {
        console.error(`[MCP] Restart attempt for "${name}" failed: ${err.message}`);
      }
      this.broadcastHealth();
    }, delay);
  }

  getServerHealth(): Record<string, { status: string; consecutiveCrashes: number; lastCrashTime?: string; lastSuccessfulConnect?: string }> {
    const config = this.getConfig();
    const health: Record<string, any> = {};
    for (const [name] of Object.entries(config)) {
      const tracker = this.crashTrackers.get(name);
      const isRestarting = !!tracker?.restartTimer;
      health[name] = {
        status: isRestarting ? 'restarting'
          : this.servers.has(name) ? 'connected'
          : (tracker?.consecutiveCrashes ?? 0) >= 5 ? 'failed'
          : (tracker?.consecutiveCrashes ?? 0) > 0 ? 'crashed'
          : 'disconnected',
        consecutiveCrashes: tracker?.consecutiveCrashes || 0,
        lastCrashTime: tracker?.lastCrashTime || undefined,
        lastSuccessfulConnect: tracker?.lastSuccessfulConnect || undefined,
      };
    }
    return health;
  }

  private broadcastHealth(): void {
    if (this.ioRef) {
      this.ioRef.emit('mcp:health_update', { servers: this.getServerHealth() });
    }
  }

  getConnectedServers(): string[] {
    return Array.from(this.servers.keys());
  }
}

export const mcpManager = new MCPClientManager();
export { SKILLS_DIR };
